# Chapter 04 제출 답안. pandas로 데이터에 질문하기

## 0. 제출 정보
- 이름: 장태진
- GitHub ID: Taejin-AI
- 작성일: 2026.10.15
- 최종 제출 URL: https://github.com/Taejin-AI/llm-data-analysis-study/blob/master/chapter04/chapter04.ipynb

## 1. 질문과 필요한 데이터 선택

### 내가 확인하려는 질문
> **분석 기간 2025-07-01 ~ 2026-07-31(주문일 `orders.order_date` 기준, 양 끝 포함) 동안, `completed` 주문의 상품 주문 금액(`quantity × unit_price` 합계)이 가장 큰 상품 카테고리는 무엇인가?**

- 분석 기간은 달력 기준 13개월로 고정했습니다. 아래 실제 데이터 검증에서 원본 주문일이 2025-07-09 ~ 2026-07-08로 이 기간 안에 모두 들어오는 것을 확인했습니다. 그래서 기간 필터로 제외되는 주문은 0건입니다. 다만 첫 달(2025-07, 9일부터)과 마지막 달(2026-07, 8일까지)은 **부분 월**이라 월별 비교에서는 따로 표시합니다.

### 계산 기준
| 항목 | 정의 |
| --- | --- |
| 분석 기간 | 2025-07-01 ~ 2026-07-31 (주문일 기준, 양 끝 날짜 포함. 코드에서는 `2025-07-01 <= order_date < 2026-08-01`) |
| 포함할 주문 상태 | `order_status == "completed"`만 포함. `cancelled`, `refunded` 제외 |
| 금액 계산식 | `line_total = quantity × unit_price` (주문 시점 단가 `order_items.unit_price` 사용, 상품 정가 `products.price`는 금액 계산에 쓰지 않음) |
| 금액의 이름 | **상품 주문 금액**. 할인·쿠폰·배송비·세금·실제 결제액 정보가 없으므로 회계상 매출·순매출·이익과 같다고 보지 않음. 과제 지정 컬럼명 `total_sales`는 이 상품 주문 금액의 합계를 뜻함 |
| 최종 집계 기준 | `products.category`별 `total_sales = sum(line_total)`, `total_quantity = sum(quantity)`, 주문 수 = `order_id.nunique()` |

### 사용한 파일/컬럼 — 필요한 컬럼과 출처 테이블(테이블 연결 관계)
| 필요한 정보 | 컬럼 | 출처 테이블 | 연결 방법 |
| --- | --- | --- | --- |
| 금액 계산 | `quantity`, `unit_price` | `order_items` | 기준 테이블(1행 = 주문 상세 1건) |
| completed 필터 | `order_status` | `orders` | `order_items.order_id` → `orders.order_id` (N:1) |
| 분석 기간·월 | `order_date` | `orders` | 위와 같은 연결 |
| 고객별 집계 | `customer_id` | `orders` | 위와 같은 연결 |
| 카테고리·상품명 | `category`, `product_name` | `products` | `order_items.product_id` → `products.product_id` (N:1) |

- **사용할 데이터: `order_items.csv`, `orders.csv`, `products.csv` 3개**
- `order_items`만으로는 상태·기간·카테고리를 알 수 없습니다. 그래서 `orders`와 `products`를 반드시 연결해야 합니다.
- `customers.csv`는 사용하지 않습니다. 고객별 집계에 필요한 `customer_id`가 `orders`에 있고, 이 질문에는 고객의 나이·성별·도시가 필요하지 않기 때문입니다. 필요 없는 개인정보 테이블을 불러오지 않는 것이 개인정보 최소화 원칙에도 맞습니다.
- 그래서 실습 가이드의 customers 관련 단계(STEP 2의 4개 CSV 로드 중 customers, STEP 4의 고객 나이·도시 필터, STEP 10의 고객 도시 병합)는 이 질문의 범위 밖이라 의도적으로 생략했습니다. 필터 실습은 질문에 필요한 기간·상태 필터로 수행했습니다(2번).

In [1]:
from pathlib import Path
import sys

import pandas as pd


def find_project_root(start_path):
    start_path = Path(start_path).resolve()
    for candidate in [start_path, *start_path.parents]:
        if (candidate / 'requirements.txt').exists() and (candidate / 'scripts').exists():
            return candidate
    raise FileNotFoundError('프로젝트 루트 폴더를 찾을 수 없습니다.')


PROJECT_ROOT = find_project_root(Path.cwd())
DATA_DIR = PROJECT_ROOT / 'data' / 'raw'
REPORT_DIR = PROJECT_ROOT / 'reports'
REPORT_DIR.mkdir(parents=True, exist_ok=True)

ANALYSIS_START = pd.Timestamp('2025-07-01')
ANALYSIS_END = pd.Timestamp('2026-07-31')
ANALYSIS_END_EXCL = pd.Timestamp('2026-08-01')   # 시간 정보가 있어도 마지막 날이 빠지지 않도록 '다음 날 미만'으로 비교

print('Python:', sys.version.split()[0], '| pandas:', pd.__version__)
print('프로젝트 루트:', PROJECT_ROOT.name)
print('데이터 폴더:', DATA_DIR.relative_to(PROJECT_ROOT), '| 결과 폴더:', REPORT_DIR.relative_to(PROJECT_ROOT))
print('분석 기간:', ANALYSIS_START.date(), '~', ANALYSIS_END.date())

Python: 3.13.16 | pandas: 3.0.5
프로젝트 루트: llm-data-analysis-course
데이터 폴더: data/raw | 결과 폴더: reports
분석 기간: 2025-07-01 ~ 2026-07-31

In [2]:
# 필요한 3개 파일만 불러오기 (customers.csv는 이 질문에 필요 없음)
required_files = ['orders.csv', 'order_items.csv', 'products.csv']
missing_files = [name for name in required_files if not (DATA_DIR / name).exists()]
if missing_files:
    raise FileNotFoundError('필요한 데이터 파일이 없습니다: ' + ', '.join(missing_files))

orders = pd.read_csv(DATA_DIR / 'orders.csv')
order_items = pd.read_csv(DATA_DIR / 'order_items.csv')
products = pd.read_csv(DATA_DIR / 'products.csv')

datasets = {'orders': orders, 'order_items': order_items, 'products': products}
expected_columns = {
    'orders': ['order_id', 'customer_id', 'order_date', 'order_status'],
    'order_items': ['order_id', 'product_id', 'quantity', 'unit_price'],
    'products': ['product_id', 'product_name', 'category'],
}
for name, df in datasets.items():
    missing = [col for col in expected_columns[name] if col not in df.columns]
    print(f'{name:12s} {str(df.shape):10s} {df.columns.tolist()}')
    if missing:
        raise KeyError(f'{name}에 필요한 컬럼이 없습니다: {missing}')

orders       (300, 5)   ['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']
order_items  (764, 5)   ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']
products     (100, 4)   ['product_id', 'product_name', 'category', 'price']

In [3]:
# [실제 데이터 검증 1] 결측·전체 중복·PK 중복·타입
PK = {'orders': 'order_id', 'order_items': 'order_item_id', 'products': 'product_id'}
quality = pd.DataFrame([
    {'table': n, 'rows': len(df), 'missing_cells': int(df.isna().sum().sum()), 'duplicated_rows': int(df.duplicated().sum()),
     'pk': PK[n], 'pk_duplicated': int(df[PK[n]].duplicated().sum()), 'pk_null': int(df[PK[n]].isna().sum())}
    for n, df in datasets.items()
])
display(quality)
print('dtypes →', {c: str(t) for c, t in order_items[['quantity', 'unit_price']].dtypes.items()},
      '| order_date:', str(orders['order_date'].dtype))

# [실제 데이터 검증 2] 날짜 범위와 변환 실패
order_dt = pd.to_datetime(orders['order_date'], format='%Y-%m-%d', errors='coerce')
print('\norder_date 변환 실패:', int(order_dt.isna().sum()), '| 범위:', order_dt.min().date(), '~', order_dt.max().date(),
      '| 분석 기간 밖 주문:', int((~((order_dt >= ANALYSIS_START) & (order_dt < ANALYSIS_END_EXCL))).sum()))

# [실제 데이터 검증 3] order_status 실제 값과 건수, category 실제 값과 상품 수
display(orders['order_status'].value_counts(dropna=False).rename('orders').to_frame().T)
display(products['category'].value_counts(dropna=False).rename('products').to_frame().T)

# [실제 데이터 검증 4] quantity·unit_price 범위와 0 이하 값
display(order_items[['quantity', 'unit_price']].describe().loc[['count', 'min', '50%', 'max']].T
        .assign(le_zero=[int((order_items['quantity'] <= 0).sum()), int((order_items['unit_price'] <= 0).sum())],
                null=[int(order_items['quantity'].isna().sum()), int(order_items['unit_price'].isna().sum())]))

# [실제 데이터 검증 5] FK 연결 상태
print('order_items.order_id   → orders.order_id     없는 값:', int((~order_items['order_id'].isin(orders['order_id'])).sum()))
print('order_items.product_id → products.product_id 없는 값:', int((~order_items['product_id'].isin(products['product_id'])).sum()))
print('주문 상세가 없는 orders:', int((~orders['order_id'].isin(order_items['order_id'])).sum()))

,table,rows,missing_cells,duplicated_rows,pk,pk_duplicated,pk_null
0,orders,300,0,0,order_id,0,0
1,order_items,764,0,0,order_item_id,0,0
2,products,100,0,0,product_id,0,0

dtypes → {'quantity': 'int64', 'unit_price': 'int64'} | order_date: str

order_date 변환 실패: 0 | 범위: 2025-07-09 ~ 2026-07-08 | 분석 기간 밖 주문: 0

order_status  completed  cancelled  refunded
orders              184         64        52

category  스포츠  전자기기  생활용품  뷰티  도서  패션  식품
products   19    17    16  16  14  11   7

            count     min       50%       max  le_zero  null
quantity    764.0     1.0       3.0       5.0        0     0
unit_price  764.0  5000.0  111000.0  200000.0        0     0

order_items.order_id   → orders.order_id     없는 값: 0
order_items.product_id → products.product_id 없는 값: 0
주문 상세가 없는 orders: 0

![분석 질문, 계산 기준, 실제 데이터 검증](images/step01_question.png)

### 결과 관찰
- 3개 파일 모두 필요한 컬럼이 있습니다: `orders` (300, 5), `order_items` (764, 5), `products` (100, 4)
- 결측 셀 0, 전체 중복 행 0입니다. PK(`order_id`, `order_item_id`, `product_id`)는 중복 0, 결측 0입니다.
- `order_date`는 변환 실패 0건이고, 범위는 **2025-07-09 ~ 2026-07-08**입니다. 분석 기간 밖 주문은 0건입니다.
- `order_status` 실제 값은 `completed` 184, `cancelled` 64, `refunded` 52, 세 가지뿐입니다.
- `category` 실제 값은 7개입니다: 스포츠 19, 전자기기 17, 생활용품 16, 뷰티 16, 도서 14, 패션 11, 식품 7(상품 수)
- `quantity`는 1~5, `unit_price`는 5,000~200,000입니다. 0 이하 값과 결측은 모두 0건입니다.
- FK 연결: `order_items`의 `order_id`, `product_id`는 모두 상대 테이블에 존재합니다(없는 값 0). 주문 상세가 없는 주문도 0건입니다.

### 나의 해석과 판단
- 필터 값 `"completed"`는 실제 값과 정확히 같습니다. 대소문자나 한글 표기가 섞여 있지 않으므로 표준화 없이 그대로 필터에 쓸 수 있다고 판단했습니다.
- `quantity`와 `unit_price`에 0, 음수, 결측이 없습니다. 그래서 `line_total`을 모든 행에 그대로 계산할 수 있고, 반품·증정품 처리 규칙이 필요하지 않습니다.
- PK가 고유하고 FK가 모두 연결되므로 N:1 병합을 해도 행이 복제되거나 빠지지 않는 구조입니다. 실제 병합 결과는 3번에서 다시 검증합니다.
- 질문에 필요한 정보는 `order_items`(금액) + `orders`(상태·기간·고객) + `products`(카테고리) 3개 테이블로 모두 해결되므로 `customers.csv`는 제외했습니다.

### 업무·분석적 의미
- 기간·상태·금액식·집계 단위를 코드보다 먼저 고정해 두었습니다. 그래서 같은 데이터로 누가 다시 계산해도 같은 숫자가 나오는 재현 가능한 질문이 됩니다.
- 데이터 품질 검증 결과(결측·중복·0 이하 값 0건)를 남겨 두면, 이후 결과가 이상할 때 원인을 데이터 품질이 아니라 계산 과정에서 찾을 수 있습니다.

### 한계와 추가 확인 사항
- 할인·쿠폰·배송비·세금·실결제 금액 컬럼이 없어서 "상품 주문 금액"이 실제 결제액과 얼마나 다른지는 이 데이터로 확인할 수 없습니다.
- `order_status`는 최종 상태 하나만 있습니다. 그래서 언제 취소·환불되었는지는 알 수 없습니다.

## 2. 필터링·정렬·파생 컬럼

In [4]:
# 파생 컬럼: line_total = quantity × unit_price (주문 상세 1행의 상품 주문 금액)
order_items = order_items.copy()
order_items['line_total'] = order_items['quantity'] * order_items['unit_price']
display(order_items[['order_id', 'product_id', 'quantity', 'unit_price', 'line_total']].head())
print('line_total 결측:', int(order_items['line_total'].isna().sum()),
      '| 0 이하:', int((order_items['line_total'] <= 0).sum()),
      '| 범위:', f"{order_items['line_total'].min():,} ~ {order_items['line_total'].max():,}")

# 필터 조건: 분석 기간 + completed (주문 단위로 먼저 확인)
orders = orders.copy()
orders['order_date'] = pd.to_datetime(orders['order_date'], format='%Y-%m-%d', errors='coerce')
in_period = (orders['order_date'] >= ANALYSIS_START) & (orders['order_date'] < ANALYSIS_END_EXCL)
is_completed = orders['order_status'] == 'completed'
filter_steps = pd.DataFrame([
    ['전체 주문', len(orders)],
    ['① 분석 기간 내', int(in_period.sum())],
    ['② ① + order_status == completed', int((in_period & is_completed).sum())],
], columns=['조건', '주문 수'])
display(filter_steps)

# 정렬: 주문 상세 금액이 큰 순서 Top 5 (상태 구분 전)
display(order_items.sort_values(['line_total', 'order_item_id'], ascending=[False, True]).head(5)
        [['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'line_total']])

   order_id  product_id  quantity  unit_price  line_total
0         1         100         3      102000      306000
1         1          87         5       25000      125000
2         1           7         3      142000      426000
3         1           9         3      193000      579000
4         2          72         4      189000      756000

line_total 결측: 0 | 0 이하: 0 | 범위: 5,000 ~ 1,000,000

                                조건  주문 수
0                            전체 주문   300
1                        ① 분석 기간 내   300
2  ② ① + order_status == completed   184

     order_item_id  order_id  product_id  quantity  unit_price  line_total
22              23        10          99         5      200000     1000000
85              86        39          99         5      200000     1000000
183            184        76          99         5      200000     1000000
78              79        35          70         5      198000      990000
493            494       190          70         5      198000      990000

- 적용한 필터 조건:
  - ① 주문일 2025-07-01 ~ 2026-07-31 → 300건 중 300건 유지
  - ② `order_status == "completed"` → **184건**
- 정렬 기준: `line_total` 내림차순(같은 값이면 `order_item_id` 오름차순으로 순서 고정)
- 만든 파생 컬럼: `line_total`
- `line_total` 계산식: `quantity × unit_price` (예: order_id 1 첫 행 3 × 102,000 = 306,000)

![필터와 파생 컬럼](images/step02_transform.png)

### 결과 관찰
- `line_total`은 764행 모두 계산되었습니다. 결측 0, 0 이하 0건이고, 범위는 5,000 ~ 1,000,000입니다.
- 기간 필터로는 한 건도 빠지지 않았고, 상태 필터로 300건 중 116건(cancelled 64 + refunded 52)이 빠졌습니다.
- 금액 Top 5 주문 상세는 모두 수량 5개 × 단가 198,000 ~ 200,000 조합입니다.

### 나의 해석과 판단
필터 기준이 바뀌면 결과가 직접 바뀝니다.
- **상태 필터를 빼면** 주문 상세 764행 전체(255,610,000)가 집계됩니다. completed 기준보다 106,620,000 커집니다(3번 병합 셀, 6-1번에서 확인). 카테고리 순위도 바뀌어 뷰티가 4위에서 2위가 됩니다(4번 견고성 표).
- **기간을 완전한 월(2025-08-01 ~ 2026-06-30)로 줄이면** 부분 월의 completed 주문(2025-07 8건, 2026-07 2건)이 빠집니다. 그래도 카테고리 순위 1~7위는 그대로였습니다(4번 견고성 표, 스포츠 31,093,000으로 1위).
- 이번 질문은 데이터 전 기간을 대상으로 하므로 기간을 2025-07-01 ~ 2026-07-31로 고정했습니다. 지금은 기간 필터가 0건을 제외하지만, 데이터가 추가되어도 결과가 달라지지 않도록 코드에 그대로 남겼습니다.

### 업무·분석적 의미
- 같은 이름의 합계라도 어떤 필터를 거쳤는지에 따라 의미가 달라집니다. 숫자를 보고할 때는 "기간·상태" 조건을 반드시 함께 적어야 합니다.

### 한계와 추가 확인 사항
- 반품을 음수 수량으로 기록하는 시스템이라면 `line_total`의 의미가 달라집니다. 이번 데이터에는 음수 수량이 없음을 1번에서 확인했습니다.

## 3. merge 검증

In [5]:
# [병합 1] order_items(N) ← orders(1): 상태·주문일·고객 연결
print('orders.order_id 중복 수:', orders['order_id'].duplicated().sum())

order_sales = order_items.merge(
    orders[['order_id', 'customer_id', 'order_date', 'order_status']],
    on='order_id', how='left', validate='many_to_one', indicator=True,
)
print('병합 전 행 수:', len(order_items), '| 병합 후 행 수:', len(order_sales), '| 일치:', len(order_items) == len(order_sales))
display(order_sales['_merge'].value_counts().to_frame('rows').T)
print('병합 후 order_status 결측:', int(order_sales['order_status'].isna().sum()),
      f"| line_total 합계 병합 전 {order_items['line_total'].sum():,} → 병합 후 {order_sales['line_total'].sum():,}")
assert len(order_items) == len(order_sales) and (order_sales['_merge'] == 'left_only').sum() == 0
order_sales = order_sales.drop(columns='_merge')

# 분석 범위 적용: 기간 + completed
in_scope_period = (order_sales['order_date'] >= ANALYSIS_START) & (order_sales['order_date'] < ANALYSIS_END_EXCL)
scope = in_scope_period & (order_sales['order_status'] == 'completed')
completed_order_sales = order_sales[scope].copy()
completed_order_sales['order_month'] = completed_order_sales['order_date'].dt.strftime('%Y-%m')
print('\n분석 범위 주문 상세 행:', len(completed_order_sales), '| 주문 수(order_id.nunique):', completed_order_sales['order_id'].nunique(),
      f"| 분석 범위 line_total 합계: {completed_order_sales['line_total'].sum():,} (범위 밖 {order_sales['line_total'].sum() - completed_order_sales['line_total'].sum():,})")
print('범위 내 order_status 값:', completed_order_sales['order_status'].unique().tolist(),
      '| 주문일 범위:', completed_order_sales['order_date'].min().date(), '~', completed_order_sales['order_date'].max().date(),
      '| order_month 결측:', int(completed_order_sales['order_month'].isna().sum()))

orders.order_id 중복 수: 0
병합 전 행 수: 764 | 병합 후 행 수: 764 | 일치: True

_merge  both  left_only  right_only
rows     764          0           0

병합 후 order_status 결측: 0 | line_total 합계 병합 전 255,610,000 → 병합 후 255,610,000

분석 범위 주문 상세 행: 474 | 주문 수(order_id.nunique): 184 | 분석 범위 line_total 합계: 148,990,000 (범위 밖 106,620,000)
범위 내 order_status 값: ['completed'] | 주문일 범위: 2025-07-09 ~ 2026-07-05 | order_month 결측: 0

In [6]:
# [병합 2] 분석 범위 주문 상세(N) ← products(1): 카테고리·상품명 연결
print('products.product_id 중복 수:', products['product_id'].duplicated().sum())

completed_sales_items = completed_order_sales.merge(
    products[['product_id', 'product_name', 'category', 'price']],
    on='product_id', how='left', validate='many_to_one', indicator=True,
)
print('병합 전 행 수:', len(completed_order_sales), '| 병합 후 행 수:', len(completed_sales_items),
      '| 일치:', len(completed_order_sales) == len(completed_sales_items))
display(completed_sales_items['_merge'].value_counts().to_frame('rows').T)
print('병합 후 category 결측:', int(completed_sales_items['category'].isna().sum()),
      f"| line_total 합계 병합 전 {completed_order_sales['line_total'].sum():,} → 병합 후 {completed_sales_items['line_total'].sum():,}")
print('unit_price ≠ products.price 행 수:', int((completed_sales_items['unit_price'] != completed_sales_items['price']).sum()))
assert len(completed_order_sales) == len(completed_sales_items) and (completed_sales_items['_merge'] == 'left_only').sum() == 0
completed_sales_items = completed_sales_items.drop(columns='_merge')

products.product_id 중복 수: 0
병합 전 행 수: 474 | 병합 후 행 수: 474 | 일치: True

_merge  both  left_only  right_only
rows     474          0           0

병합 후 category 결측: 0 | line_total 합계 병합 전 148,990,000 → 병합 후 148,990,000
unit_price ≠ products.price 행 수: 0

| 병합 | key | `validate` 결과 | 병합 전 → 후 행 수 | `indicator` 결과 | key 중복 | 판정 |
| --- | --- | --- | --- | --- | --- | --- |
| `order_items` ← `orders` | `order_id` | `many_to_one` 통과 | 764 → 764 | both 764 / left_only 0 | `orders.order_id` 0 | PASS |
| 분석 범위 주문 상세 ← `products` | `product_id` | `many_to_one` 통과 | 474 → 474 | both 474 / left_only 0 | `products.product_id` 0 | PASS |

- 병합한 데이터: `order_items` + `orders`(상태·주문일·고객), 분석 범위 주문 상세 + `products`(상품명·카테고리)
- 사용한 key: `order_id`, `product_id`
- `validate` 결과: 두 병합 모두 `MergeError` 없이 통과
- `indicator` 결과: `left_only` 0, `right_only` 0 (`how='left'`이므로 `right_only`는 생기지 않음)
- 병합 전/후 행 수: 764 → 764, 474 → 474

![merge 검증](images/step03_merge.png)

### 결과 관찰
- 두 병합 모두 행 수가 그대로이고, 미매칭과 key 중복은 0건입니다. 병합 후 `order_status`, `category` 결측도 0입니다.
- 병합 전후 `line_total` 합계가 같습니다: 255,610,000 → 255,610,000(orders 병합), 148,990,000 → 148,990,000(products 병합). 분석 범위 밖(취소·환불) 금액은 106,620,000입니다.
- 분석 범위(기간 + completed)는 주문 상세 474행, 주문 184건입니다. 범위 안의 상태 값은 `completed`만 있습니다.
- 주문 단가 `unit_price`와 상품 정가 `price`가 다른 행은 0건입니다.

### 나의 해석과 판단
이번 병합이 안전하다고 판단한 근거는 네 가지입니다.
1. 오른쪽 key가 고유합니다. `validate='many_to_one'`이 이를 강제로 확인했으므로 왼쪽 행이 복제될 수 없습니다.
2. 병합 전후 행 수가 같습니다. 복제도 손실도 없습니다.
3. `left_only` 0건입니다. 모든 주문 상세가 상태·기간·카테고리 정보를 받았습니다.
4. 병합 전후 금액 합계가 같습니다.

행 수가 늘거나 줄지 않았으므로 따로 설명할 증감은 없습니다. 행이 늘었다면 오른쪽 key 중복을, 줄었다면 `inner` 병합이나 필터 순서를 먼저 확인했을 것입니다.

### 업무·분석적 의미
잘못된 merge는 오류 없이 금액을 바꿉니다.
- **복제(과대)**: 상품 마스터에 같은 `product_id`가 두 번 있으면 그 상품의 주문 금액이 두 배로 잡힙니다.
- **누락(과소)**: `how='left'`인데 미매칭이 있으면 `order_status`가 NaN이 되어 completed 필터에서 조용히 빠집니다.

그래서 merge는 "실행 성공"이 아니라 **행 수 + validate + indicator + 합계**로 확인해야 합니다.

### 한계와 추가 확인 사항
- `validate`는 key의 개수 관계만 확인합니다. key 값은 맞지만 다른 상품으로 잘못 매핑된 경우는 잡지 못합니다.
- 상품 마스터가 주문 시점이 아닌 현재 기준이라면, 그 사이 카테고리가 바뀐 상품이 있어도 이 데이터로는 확인할 수 없습니다.

## 4. completed 주문 범위와 집계

In [7]:
# [핵심 질문] 카테고리별 completed 상품 주문 금액 (분석 기간 2025-07-01 ~ 2026-07-31)
category_sales = (
    completed_sales_items
    .groupby('category', as_index=False)
    .agg(
        total_sales=('line_total', 'sum'),
        total_quantity=('quantity', 'sum'),
        order_count=('order_id', 'nunique'),
        customer_count=('customer_id', 'nunique'),
        product_count=('product_id', 'nunique'),
    )
    .sort_values('total_sales', ascending=False)
    .reset_index(drop=True)
)
category_sales['amount_ratio(%)'] = (category_sales['total_sales'] / category_sales['total_sales'].sum() * 100).round(2)
category_sales['amount_per_product'] = (category_sales['total_sales'] / category_sales['product_count']).round(0)
display(category_sales)
top = category_sales.loc[0]
print(f"답: completed 상품 주문 금액 1위 카테고리 = {top['category']} ({top['total_sales']:,}, {top['amount_ratio(%)']}%)",
      f"| 2위와 차이 {top['total_sales'] - category_sales.loc[1, 'total_sales']:,}")
print('카테고리별 order_count 합계:', category_sales['order_count'].sum(), '/ 실제 completed 주문 수:', completed_sales_items['order_id'].nunique())

,category,total_sales,total_quantity,order_count,customer_count,product_count,amount_ratio(%),amount_per_product
0,스포츠,31743000,295,85,67,18,21.31,1763500.0
1,전자기기,26400000,259,60,44,17,17.72,1552941.0
2,생활용품,23915000,272,65,50,16,16.05,1494688.0
3,뷰티,23383000,223,65,53,16,15.69,1461438.0
4,식품,16573000,133,36,31,7,11.12,2367571.0
5,도서,16389000,149,52,46,13,11.00,1260692.0
6,패션,10587000,111,33,27,11,7.11,962455.0

답: completed 상품 주문 금액 1위 카테고리 = 스포츠 (31,743,000, 21.31%) | 2위와 차이 5,343,000
카테고리별 order_count 합계: 396 / 실제 completed 주문 수: 184

In [8]:
# [결과 견고성 확인] 같은 기준을 모든 카테고리에 똑같이 적용
# ① 카테고리마다 1위 상품을 하나씩 뺐을 때 순위  ② 완전한 월(2025-08~2026-06)만 썼을 때 순위  ③ 상태 필터 전 금액 대비 completed 비율
prod_by_cat = (completed_sales_items.groupby(['category', 'product_id'])['line_total'].sum()
               .reset_index().sort_values(['category', 'line_total'], ascending=[True, False]))
top_prod = prod_by_cat.groupby('category').head(1).set_index('category')
robust = category_sales.set_index('category')[['total_sales']].copy()
robust['top_product_id'] = top_prod['product_id']
robust['top_product_amount'] = top_prod['line_total']
robust['top_product_share(%)'] = (robust['top_product_amount'] / robust['total_sales'] * 100).round(1)
robust['without_top_product'] = robust['total_sales'] - robust['top_product_amount']
robust['rank_all'] = robust['total_sales'].rank(ascending=False).astype(int)
robust['rank_without_top'] = robust['without_top_product'].rank(ascending=False).astype(int)

full_months = completed_sales_items[(completed_sales_items['order_date'] >= '2025-08-01') & (completed_sales_items['order_date'] < '2026-07-01')]
robust['full_months_amount'] = full_months.groupby('category')['line_total'].sum()
robust['rank_full_months'] = robust['full_months_amount'].rank(ascending=False).astype(int)

all_status = (order_sales[in_scope_period]
              .merge(products[['product_id', 'category']], on='product_id', how='left', validate='many_to_one')
              .groupby('category')['line_total'].sum())
robust['all_status_amount'] = all_status
robust['rank_all_status'] = robust['all_status_amount'].rank(ascending=False).astype(int)
robust['completed_ratio(%)'] = (robust['total_sales'] / robust['all_status_amount'] * 100).round(1)
display(robust)

# 1위 카테고리의 1위 상품이 특정 고객·월에 몰려 있는지
top_cat = category_sales.loc[0, 'category']
t = completed_sales_items[completed_sales_items['product_id'] == robust.loc[top_cat, 'top_product_id']]
print(f"{top_cat} 1위 상품 {robust.loc[top_cat, 'top_product_id']}: 주문 {t['order_id'].nunique()}건, 고객 {t['customer_id'].nunique()}명, "
      f"행당 최대 수량 {t['quantity'].max()}, 고객 1명 최대 비중 {t.groupby('customer_id')['line_total'].sum().max() / t['line_total'].sum():.1%}, "
      f"월 최대 {t['order_month'].value_counts().max()}건({t['order_month'].value_counts().idxmax()}, 주문 {t['order_id'].nunique()}건 중 {t['order_month'].value_counts().max() / t['order_id'].nunique():.0%})")

,total_sales,top_product_id,top_product_amount,top_product_share(%),without_top_product,rank_all,rank_without_top,full_months_amount,rank_full_months,all_status_amount,rank_all_status,completed_ratio(%)
category,,,,,,,,,,,,
스포츠,31743000,41,5705000,18.0,26038000,1,1,31093000,1,50174000,1,63.3
전자기기,26400000,71,3703000,14.0,22697000,2,2,23927000,2,41003000,3,64.4
생활용품,23915000,22,3248000,13.6,20667000,3,3,22238000,3,34839000,4,68.6
뷰티,23383000,72,3780000,16.2,19603000,4,4,22047000,4,47551000,2,49.2
식품,16573000,12,4375000,26.4,12198000,5,6,15650000,5,33597000,5,49.3
도서,16389000,73,2964000,18.1,13425000,6,5,15391000,6,24645000,6,66.5
패션,10587000,11,3565000,33.7,7022000,7,7,10587000,7,23801000,7,44.5

스포츠 1위 상품 41: 주문 12건, 고객 11명, 행당 최대 수량 5, 고객 1명 최대 비중 14.3%, 월 최대 4건(2026-01, 주문 12건 중 33%)

In [9]:
# 상품별 집계
product_sales = (
    completed_sales_items
    .groupby(['product_id', 'product_name', 'category'], as_index=False)
    .agg(total_sales=('line_total', 'sum'), total_quantity=('quantity', 'sum'), order_count=('order_id', 'nunique'))
    .sort_values('total_sales', ascending=False)
)
display(product_sales.head(10))
print('completed 주문이 있는 상품 수:', len(product_sales), '/ 전체 상품 수:', len(products))

    product_id product_name category  total_sales  total_quantity  order_count
39          41   스포츠 상품 041      스포츠      5705000              35           12
11          12    식품 상품 012       식품      4375000              25            7
8            9   스포츠 상품 009      스포츠      3860000              20            6
70          72    뷰티 상품 072       뷰티      3780000              20            6
69          71  전자기기 상품 071     전자기기      3703000              23            5
66          68   스포츠 상품 068      스포츠      3640000              26            8
78          81  전자기기 상품 081     전자기기      3630000              22            6
10          11    패션 상품 011       패션      3565000              31            7
20          22  생활용품 상품 022     생활용품      3248000              29            8
86          89  생활용품 상품 089     생활용품      3090000              30           11

completed 주문이 있는 상품 수: 98 / 전체 상품 수: 100

In [10]:
# 월별 집계 (order_count = order_id.nunique) + 부분 월 표시
monthly_summary = (
    completed_order_sales
    .groupby('order_month', as_index=False)
    .agg(total_sales=('line_total', 'sum'), order_count=('order_id', 'nunique'),
         first_date=('order_date', 'min'), last_date=('order_date', 'max'))
    .sort_values('order_month')
)
monthly_summary['average_order_value'] = (monthly_summary['total_sales'] / monthly_summary['order_count']).round(0)
data_first, data_last = orders['order_date'].min(), orders['order_date'].max()
monthly_summary['partial_month'] = monthly_summary['order_month'].isin([data_first.strftime('%Y-%m'), data_last.strftime('%Y-%m')])
display(monthly_summary.drop(columns=['first_date', 'last_date']))
full = monthly_summary[~monthly_summary['partial_month']]
print(f"완전한 월 {len(full)}개: total_sales와 order_count 상관계수 r = {full['total_sales'].corr(full['order_count']):.2f}",
      f"| 평균 주문 금액 범위 {full['average_order_value'].min():,.0f} ~ {full['average_order_value'].max():,.0f}")

# 월별 금액 변화가 주문 수 때문인지 완료율 때문인지 분리 (전체 상태 기준 주문 수)
period_orders = orders[in_period]
monthly_status = pd.crosstab(period_orders['order_date'].dt.strftime('%Y-%m'), period_orders['order_status'])
monthly_status['all_orders'] = monthly_status.sum(axis=1)
monthly_status['completion_rate(%)'] = (monthly_status['completed'] / monthly_status['all_orders'] * 100).round(1)
display(monthly_status)
print('전체 완료율(%):', round(is_completed.mean() * 100, 1))

   order_month  total_sales  order_count  average_order_value  partial_month
0      2025-07      5869000            8             733625.0           True
1      2025-08     15621000           18             867833.0          False
2      2025-09     10190000           13             783846.0          False
3      2025-10     25766000           26             991000.0          False
4      2025-11      8812000           12             734333.0          False
5      2025-12     11501000           14             821500.0          False
6      2026-01     17423000           22             791955.0          False
7      2026-02      9749000           17             573471.0          False
8      2026-03     13429000           14             959214.0          False
9      2026-04     17553000           23             763174.0          False
10     2026-05      8063000           11             733000.0          False
11     2026-06      2826000            4             706500.0          False
12     2026-07      2188000            2            1094000.0           True

완전한 월 11개: total_sales와 order_count 상관계수 r = 0.94 | 평균 주문 금액 범위 573,471 ~ 991,000

order_status  cancelled  completed  refunded  all_orders  completion_rate(%)
order_date
2025-07               3          8         4          15                53.3
2025-08               5         18         1          24                75.0
2025-09               6         13         4          23                56.5
2025-10              10         26         3          39                66.7
2025-11               4         12         7          23                52.2
2025-12               9         14         3          26                53.8
2026-01               3         22         4          29                75.9
2026-02               5         17         7          29                58.6
2026-03               6         14         1          21                66.7
2026-04               5         23         3          31                74.2
2026-05               1         11         8          20                55.0
2026-06               6          4         6          16                25.0
2026-07               1          2         1           4                50.0

전체 완료율(%): 61.3

In [11]:
# 고객별 집계 (customer_id는 orders에서 가져옴 → customers.csv 불필요)
customer_sales = (
    completed_order_sales
    .groupby('customer_id', as_index=False)
    .agg(order_count=('order_id', 'nunique'), total_sales=('line_total', 'sum'))
    .sort_values(['total_sales', 'customer_id'], ascending=[False, True])
    .reset_index(drop=True)
)
customer_sales['customer_label'] = 'Customer ' + customer_sales['customer_id'].astype(str)
display(customer_sales[['customer_label', 'order_count', 'total_sales']].head(10))
top10_share = customer_sales['total_sales'].head(10).sum() / customer_sales['total_sales'].sum() * 100
print('completed 주문이 있는 고객 수:', len(customer_sales), '| 주문 이력이 있는 전체 고객 수:', orders['customer_id'].nunique(),
      f'| 상위 10명 금액 비중: {top10_share:.1f}% (균등 분포라면 {10 / len(customer_sales) * 100:.0f}%)',
      f"| 1위 고객 비중: {customer_sales['total_sales'].iloc[0] / customer_sales['total_sales'].sum():.1%}")

  customer_label  order_count  total_sales
0   Customer 117            5      4100000
1   Customer 102            4      3996000
2    Customer 83            4      3880000
3    Customer 30            5      3590000
4    Customer 40            4      3523000
5    Customer 20            2      3191000
6     Customer 3            2      3178000
7   Customer 111            3      3153000
8    Customer 66            4      3093000
9   Customer 147            2      2990000

completed 주문이 있는 고객 수: 100 | 주문 이력이 있는 전체 고객 수: 126 | 상위 10명 금액 비중: 23.3% (균등 분포라면 10%) | 1위 고객 비중: 2.8%

- 분석 범위 정의: 2025-07-01 ~ 2026-07-31 주문 중 `order_status == "completed"` 184건(주문 상세 474행). `total_sales` = 이 범위의 상품 주문 금액(`quantity × unit_price`) 합계 = **148,990,000**
- 카테고리별 결과: **1위 스포츠 31,743,000 (21.31%)** → 전자기기 26,400,000 (17.72%) → 생활용품 23,915,000 → 뷰티 23,383,000 → 식품 16,573,000 → 도서 16,389,000 → 패션 10,587,000 (7.11%)
- 상품별 결과: 1위 스포츠 상품 041 5,705,000 (수량 35, 주문 12건). completed 주문이 있는 상품은 98개(100개 중 2개는 없음)
- 월별 결과: 최고 2025-10 25,766,000(26건), 최저(완전한 월 기준) 2026-06 2,826,000(4건). 부분 월은 2025-07 5,869,000(8건), 2026-07 2,188,000(2건)
- 고객별 결과: completed 주문이 있는 고객 100명(주문 이력 고객 126명 중). 1위 Customer 117 4,100,000(5건). 상위 10명 비중 23.3%

![핵심 집계 결과](images/step04_groupby.png)

### 결과 관찰
**카테고리**
- **질문에 대한 답**: 분석 기간 completed 상품 주문 금액이 가장 큰 카테고리는 **스포츠(31,743,000)**입니다. 2위 전자기기보다 5,343,000(20.2%) 많습니다.
- 스포츠는 수량(295), 주문 수(85), 구매 고객 수(67), 판매 상품 수(18)도 모두 1위입니다.
- 견고성 확인(같은 기준을 모든 카테고리에 적용):
  - 카테고리마다 1위 상품을 하나씩 빼도 스포츠가 1위입니다(26,038,000 vs 전자기기 22,697,000).
  - 1위 상품 비중은 스포츠 18.0%로 7개 중 4번째입니다(패션 33.7%·식품 26.4%·도서 18.1%보다 낮고, 뷰티 16.2%·전자기기 14.0%·생활용품 13.6%보다 높음).
  - 1위 상품을 빼면 중위권에서는 식품(5→6위)과 도서(6→5위)가 바뀝니다.
  - 완전한 월(2025-08 ~ 2026-06)만 써도 1~7위 순위는 그대로입니다.
- 상태 필터 전 금액으로 보면 1위는 스포츠로 같지만 중위권이 바뀝니다: 뷰티 2위(47,551,000), 전자기기 3위
- completed 비율은 금액 기준 44.5%(패션) ~ 68.6%(생활용품)입니다. 패션 44.5%, 뷰티 49.2%, 식품 49.3%가 50% 아래입니다.
- 카테고리별 `order_count` 합계는 396으로, 실제 completed 주문 수 184보다 큽니다.

**상품**
- 상품 041은 주문 12건, 고객 11명에게 나뉘어 팔렸습니다. 행당 최대 수량은 5, 고객 1명의 최대 비중은 14.3%입니다. 월 기준으로는 2026-01에 4건(12건 중 33%)이 몰려 있습니다.
- 상위 10개 상품 중 스포츠가 3개(041·009·068)입니다.

**월별**
- 월 금액은 주문 수와 함께 움직입니다. 완전한 월 11개에서 `total_sales`와 `order_count`의 상관계수는 r = 0.94입니다. 최고 2025-10은 26건, 최저 2026-06은 4건입니다.
- 완전한 월의 평균 주문 금액은 573,471(2026-02) ~ 991,000(2025-10) 범위입니다.
- 2026-06은 전체 주문 16건, 완료율 25.0%로 전체 평균(61.3%)보다 크게 낮습니다.

**고객**
- completed 주문 고객 100명 중 상위 10명 비중은 23.3%로, 균등 분포일 때(10%)의 약 2.3배입니다. 1위 고객(4,100,000)은 전체의 2.8%입니다.

### 나의 해석과 판단
- "스포츠가 1위"라는 답은 **견고하다**고 판단했습니다. 1위 상품 하나씩 제거, 완전한 월만 사용 두 조건에서 모두 1위가 유지되고, 2위와 차이도 20%입니다. 상품 041도 특정 고객 쏠림은 없었습니다(최대 14.3%). 다만 2026-01에 주문의 1/3이 몰려 있어, 이 달의 판촉·이벤트 여부는 추가로 확인할 필요가 있습니다.
- 반면 **중위권 순위는 상태 필터와 상품 제거 모두에 민감합니다.** 1위 상품을 빼면 식품·도서가 자리를 바꿉니다. 뷰티는 주문 금액은 컸지만 금액 기준 50.8%가 취소·환불되어 2위에서 4위로 내려갑니다. 즉 카테고리 순위는 수요(주문 금액)와 완료율이 합쳐진 결과입니다.
- 카테고리 `order_count` 합계(396)가 184보다 큰 것은 오류가 아닙니다. **한 주문에 여러 카테고리 상품이 들어 있기 때문**이며, 카테고리별 주문 수를 더해 전체 주문 수로 쓰면 안 됩니다.
- 월별 변동은 주로 주문 수 변화에서 나옵니다(r = 0.94). 2026-06의 급감은 주문 수 감소(16건)와 완료율 하락(25%)이 겹친 결과입니다. 2025-07, 2026-07은 부분 월이라 다른 달과 같은 기준으로 비교하지 않았습니다.
- 상위 10명 비중은 균등 분포보다 높지만, 고객 1명의 비중은 최대 2.8%입니다. 그래서 개별 고객 한 명의 이탈이 전체 금액을 크게 흔들 구조는 아닙니다.

### 업무·분석적 의미
- 카테고리 금액 순위는 기획전·재고 배분 우선순위의 출발점이 됩니다. 스포츠 1위는 조건을 바꿔도 유지되므로 우선순위 근거로 쓸 수 있습니다.
- 뷰티·패션·식품처럼 completed 비율이 50% 아래인 카테고리는 수요를 늘리는 것보다 **취소·환불 원인**(배송 지연, 상품 품질, 기대와 다른 상품 등)을 줄이는 것이 금액을 늘리는 데 더 효과적일 수 있습니다.
- 패션은 1위 상품 비중이 33.7%로 높습니다. 이 상품의 재고나 판매 중단 여부가 카테고리 금액에 크게 영향을 줍니다.

### 한계와 추가 확인 사항
```text
total_sales가 가장 높다 ≠ 가장 인기 있는 카테고리 ≠ 가장 수익성이 높은 카테고리
```
- **인기**: 금액은 단가의 영향을 받습니다. 이번 데이터에서는 구매 고객 수도 스포츠가 1위(67명)였지만, 재구매나 만족도 데이터는 없습니다.
- **수익성**: 원가·마진 데이터가 없어 이익을 계산할 수 없습니다.
- **회계상 매출과 같다고 단정할 수 없는 이유**:
  1. 할인·쿠폰·포인트 차감 정보가 없어 `unit_price`가 최종 결제가인지 알 수 없습니다.
  2. 배송비·세금 정보가 없습니다.
  3. 환불 금액 컬럼이 없어 전액 환불인지 부분 환불인지 구분할 수 없습니다.
  4. 주문일 기준이라 회계상 매출 인식 시점(배송 완료·구매 확정일)과 다를 수 있습니다.
- completed 주문 184건 규모의 샘플이라 중위권(생활용품 23,915,000 vs 뷰티 23,383,000처럼 차이가 작은 구간)의 순위는 우연한 변동일 수 있습니다.

## 5. 총합 일치 검증

In [12]:
# 같은 범위(기간 + completed)라면: 원본 = 카테고리 = 상품 = 월 = 고객 합계
base_total = completed_order_sales['line_total'].sum()
checks = {
    '원본 completed line_total (orders 병합·범위 적용 후)': base_total,
    '원본 completed line_total (products 병합 후)': completed_sales_items['line_total'].sum(),
    '카테고리별 합계': category_sales['total_sales'].sum(),
    '상품별 합계': product_sales['total_sales'].sum(),
    '월별 합계': monthly_summary['total_sales'].sum(),
    '고객별 합계': customer_sales['total_sales'].sum(),
}
total_check = pd.DataFrame({'항목': list(checks), '합계': list(checks.values())})
total_check['기준 대비 차이'] = total_check['합계'] - base_total
total_check['결과'] = total_check['기준 대비 차이'].eq(0).map({True: 'PASS', False: 'FAIL'})
display(total_check)

print('수량  : 카테고리', category_sales['total_quantity'].sum(), '/ 상품', product_sales['total_quantity'].sum(),
      '/ 원본', completed_sales_items['quantity'].sum())
print('주문수: 월별 합', monthly_summary['order_count'].sum(), '/ 고객별 합', customer_sales['order_count'].sum(),
      '/ 원본 order_id.nunique', completed_order_sales['order_id'].nunique())
print('참고  : 카테고리별 order_count 합', category_sales['order_count'].sum(), '(한 주문이 여러 카테고리 포함 → 합산 불가)')
print('대조  : 범위 밖(취소·환불) 금액', f"{order_items['line_total'].sum() - base_total:,}", '(상태 필터를 빠뜨리면 이만큼 과대)')
assert (total_check['결과'] == 'PASS').all(), '총합 불일치 — 해석 전에 원인 확인 필요'
print('\n총합 검증: PASS')

                                            항목         합계  기준 대비 차이    결과
0  원본 completed line_total (orders 병합·범위 적용 후)  148990000         0  PASS
1      원본 completed line_total (products 병합 후)  148990000         0  PASS
2                                     카테고리별 합계  148990000         0  PASS
3                                       상품별 합계  148990000         0  PASS
4                                        월별 합계  148990000         0  PASS
5                                       고객별 합계  148990000         0  PASS

수량  : 카테고리 1442 / 상품 1442 / 원본 1442
주문수: 월별 합 184 / 고객별 합 184 / 원본 order_id.nunique 184
참고  : 카테고리별 order_count 합 396 (한 주문이 여러 카테고리 포함 → 합산 불가)
대조  : 범위 밖(취소·환불) 금액 106,620,000 (상태 필터를 빠뜨리면 이만큼 과대)

총합 검증: PASS

- 원본 completed `line_total` 합계: 148,990,000
- 카테고리 합계: 148,990,000
- 상품별 합계: 148,990,000
- 월별 합계: 148,990,000
- 고객별 합계: 148,990,000
- 차이 여부: **모든 항목 차이 0 → PASS**. 수량(1,442)도 일치하고, 월별·고객별 `order_count` 합계(184)도 `order_id.nunique()`(184)와 일치합니다.

![총합 검증](images/step05_total_check.png)

### 나의 해석과 판단
- **총합 검증이 필요한 이유**: groupby는 같은 범위를 나눠 다시 더하는 작업입니다. 그래서 어떤 기준으로 나누든 합계는 원본과 같아야 합니다. 합계가 다르면 중간에 행이 **복제**되었거나(merge key 중복), **빠졌거나**(범위 차이, NaN key 제외) 둘 중 하나입니다. 이런 문제는 집계표만 봐서는 드러나지 않습니다.
- 특히 `groupby`는 기본값(`dropna=True`)에서 key가 NaN인 행을 조용히 제외합니다. 오류 없이 합계만 작아질 수 있으므로 숫자로 비교해야 합니다.
- 주문 수는 월별·고객별처럼 **한 주문이 한 그룹에만 속하는 기준**에서만 합계가 맞아야 합니다. 카테고리처럼 한 주문이 여러 그룹에 걸치는 기준에서는 합계가 더 큰 것이 정상입니다.
- **불일치 시 확인 순서**
  1. 비교한 DataFrame들이 같은 범위(기간 + completed)인지 확인합니다.
  2. 병합 전후 행 수와 오른쪽 key 중복 수를 확인합니다(복제).
  3. `_merge`의 `left_only`와 병합 후 NaN 수를 확인합니다(미매칭).
  4. groupby key(`category`, `order_month`, `customer_id`)의 NaN 수를 확인합니다(조용한 제외).
  5. 차이 금액과 같은 금액의 행이나 주문을 찾아 원인을 특정합니다.

In [13]:
# 결과 CSV 저장 후 다시 읽어 검증
outputs = {
    'ch04_category_sales.csv': category_sales,
    'ch04_product_sales.csv': product_sales,
    'ch04_monthly_sales.csv': monthly_summary,
    'ch04_customer_sales.csv': customer_sales,
}
rows = []
for filename, df in outputs.items():
    path = REPORT_DIR / filename
    df.to_csv(path, index=False, encoding='utf-8-sig')
    check = pd.read_csv(path)
    rows.append({'file': filename, 'exists': path.exists(), 'size>0': path.stat().st_size > 0, 'shape': check.shape,
                 'columns_same': check.columns.tolist() == df.columns.tolist(),
                 'total_sales_same': check['total_sales'].sum() == df['total_sales'].sum()})
display(pd.DataFrame(rows))

,file,exists,size>0,shape,columns_same,total_sales_same
0,ch04_category_sales.csv,True,True,"(7, 8)",True,True
1,ch04_product_sales.csv,True,True,"(98, 6)",True,True
2,ch04_monthly_sales.csv,True,True,"(13, 7)",True,True
3,ch04_customer_sales.csv,True,True,"(100, 4)",True,True

- 4개 CSV가 모두 저장되었습니다. 다시 읽었을 때 컬럼과 `total_sales` 합계가 저장 전과 같았습니다. 고객 결과에는 `customer_id` 기반 라벨만 있고 개인정보는 없습니다.

## 6. LLM pandas 코드 검증

### 6-1. 공식 Notebook의 LLM 예시 코드 점검
공식 Notebook에 나온 LLM 제안 코드 `order_items.groupby('category')['line_total'].sum()`을 실제 데이터에 실행해 봤습니다.

In [14]:
try:
    order_items.groupby('category')['line_total'].sum()
except KeyError as e:
    print('KeyError 발생:', e)
print("order_items에 category 컬럼:", 'category' in order_items.columns, "| products에 category 컬럼:", 'category' in products.columns)

# products만 붙여 '실행되게만' 고친 경우 → orders(상태·기간) 연결이 없어 금액 과대
naive = (order_items.merge(products[['product_id', 'category']], on='product_id')
         .groupby('category')['line_total'].sum())
print('상태 필터 없는 카테고리 합계:', f'{naive.sum():,}', '/ completed 기준:', f"{category_sales['total_sales'].sum():,}")
print('필터 없는 순위:', naive.sort_values(ascending=False).head(3).to_dict())

KeyError 발생: 'category'
order_items에 category 컬럼: False | products에 category 컬럼: True
상태 필터 없는 카테고리 합계: 255,610,000 / completed 기준: 148,990,000
필터 없는 순위: {'스포츠': 50174000, '뷰티': 47551000, '전자기기': 41003000}

### 6-2. 이번 과제 질문으로 LLM에 코드 요청
- 사용 LLM: Claude (Anthropic)
- Prompt:

```text
orders.csv, order_items.csv, products.csv를 사용해
completed 주문 기준 카테고리별 total_sales와 total_quantity를 계산하는 pandas 코드를 작성해 주세요.

- line_total = quantity × unit_price
- orders.order_id, products.product_id 고유성 확인
- many-to-one merge + indicator
- 병합 전후 행 수와 미매칭 확인
- completed 주문만 필터링
- 카테고리별 고유 주문 수(order_count)도 계산
- 결과를 회계상 순매출이라고 단정하지 않기
```

아래 셀의 `LLM_CODE`가 LLM 응답 코드 원문입니다. 검토 순서는 다음과 같습니다.
1. 원문 그대로 실행
2. 파일 경로만 고쳐 실행한 뒤 Notebook의 `category_sales`와 대조
3. 과제 체크리스트와 테이블 연결 관계로 직접 검토
4. 검토에서 찾은 문제를 반영한 최종 코드를 실행해 다시 대조

LLM 코드는 별도 namespace에서 실행해 Notebook 변수를 덮어쓰지 않게 했습니다.

In [15]:
LLM_CODE = r"""
import pandas as pd

orders = pd.read_csv("data/raw/orders.csv")
order_items = pd.read_csv("data/raw/order_items.csv")
products = pd.read_csv("data/raw/products.csv")

# 1) 주문 상세 금액
order_items["line_total"] = order_items["quantity"] * order_items["unit_price"]

# 2) 키 고유성 확인
assert orders["order_id"].is_unique
assert products["product_id"].is_unique

# 3) 주문 상태 연결 (many-to-one)
df = order_items.merge(
    orders[["order_id", "order_status"]],
    on="order_id", how="left", validate="many_to_one", indicator=True,
)
print("orders 병합 전/후:", len(order_items), len(df))
print(df["_merge"].value_counts().to_dict())
df = df.drop(columns="_merge")

# 4) 완료 주문만
completed = df[df["order_status"] == "completed"]

# 5) 상품 카테고리 연결 (many-to-one)
completed = completed.merge(
    products[["product_id", "category"]],
    on="product_id", how="left", validate="many_to_one", indicator=True,
)
print("products 병합 후:", len(completed))
print(completed["_merge"].value_counts().to_dict())

# 6) 카테고리별 집계
category_summary = (
    completed.groupby("category", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        total_quantity=("quantity", "sum"),
        order_count=("order_id", "nunique"),
    )
    .sort_values("total_sales", ascending=False)
)
print(category_summary)
# 참고: total_sales는 completed 주문의 quantity × unit_price 합계이며 회계상 순매출이 아닙니다.
"""

# ① 원문 그대로 실행
try:
    exec(LLM_CODE, {})
except FileNotFoundError as e:
    print('① 원문 실행 결과 → FileNotFoundError:', e)
    print('   현재 작업 폴더:', Path.cwd().name, '(data/raw가 이 폴더 아래에 없음)')

① 원문 실행 결과 → FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/orders.csv'
   현재 작업 폴더: ch04 (data/raw가 이 폴더 아래에 없음)

In [16]:
# ② 경로만 DATA_DIR로 수정해서 실행 (로직은 원문 그대로) → ③ Notebook 결과와 대조
llm_code_fixed = LLM_CODE.replace('pd.read_csv("data/raw/', 'pd.read_csv(DATA_DIR / "')
llm_ns = {'DATA_DIR': DATA_DIR}
print('② 경로 수정 후 실행 출력 ↓')
exec(llm_code_fixed, llm_ns)
llm_category = llm_ns['category_summary']

compare = category_sales[['category', 'total_sales', 'total_quantity', 'order_count']].merge(
    llm_category, on='category', how='outer', suffixes=('_notebook', '_llm'), indicator=True,
)
compare['sales_diff'] = compare['total_sales_llm'] - compare['total_sales_notebook']
compare['qty_diff'] = compare['total_quantity_llm'] - compare['total_quantity_notebook']
compare['count_diff'] = compare['order_count_llm'] - compare['order_count_notebook']
print('\n③ Notebook category_sales와 대조')
display(compare[['category', 'total_sales_notebook', 'total_sales_llm', 'sales_diff', 'qty_diff', 'count_diff', '_merge']])

② 경로 수정 후 실행 출력 ↓

orders 병합 전/후: 764 764
{'both': 764, 'left_only': 0, 'right_only': 0}
products 병합 후: 474
{'both': 474, 'left_only': 0, 'right_only': 0}
  category  total_sales  total_quantity  order_count
3      스포츠     31743000             295           85
5     전자기기     26400000             259           60
2     생활용품     23915000             272           65
1       뷰티     23383000             223           65
4       식품     16573000             133           36
0       도서     16389000             149           52
6       패션     10587000             111           33

③ Notebook category_sales와 대조

,category,total_sales_notebook,total_sales_llm,sales_diff,qty_diff,count_diff,_merge
0,도서,16389000,16389000,0,0,0,both
1,뷰티,23383000,23383000,0,0,0,both
2,생활용품,23915000,23915000,0,0,0,both
3,스포츠,31743000,31743000,0,0,0,both
4,식품,16573000,16573000,0,0,0,both
5,전자기기,26400000,26400000,0,0,0,both
6,패션,10587000,10587000,0,0,0,both

In [17]:
# ④ 과제 체크리스트 + 테이블 연결 관계로 LLM 코드 직접 검토
llm_completed = llm_ns['completed']
llm_dates = pd.to_datetime(llm_ns['orders']['order_date'])
review = pd.DataFrame([
    ['실제 컬럼명을 사용했는가?', 'O', 'order_id, product_id, quantity, unit_price, order_status, category 모두 실제 컬럼'],
    ['필요한 테이블을 정확히 연결했는가?', 'O',
     '상태 ← orders.order_status, 카테고리 ← products.category, 금액 ← order_items. 불필요한 customers는 사용하지 않음'],
    ['필터 조건이 실제 데이터와 맞는가?', '△',
     "'completed'는 실제 값과 일치. 단, order_status 실제 값(value_counts) 확인 단계가 없음"],
    ['분석 기간을 적용했는가?', 'X',
     f'order_date를 불러오지 않아 기간 필터 없음. 이번 데이터는 전부 기간 안({llm_dates.min().date()}~{llm_dates.max().date()})이라 결과만 우연히 같음'],
    ['merge 관계가 올바른가?', 'O',
     f"N:1 × 2회, validate+indicator 사용, left_only={int((llm_completed['_merge'] == 'left_only').sum())}. 단, products 병합 '전' 행 수는 출력하지 않음"],
    ['completed 범위를 정확히 적용했는가?', 'O',
     f"범위 내 status {llm_completed['order_status'].unique().tolist()}, 행 수 {len(llm_completed)} = Notebook {len(completed_sales_items)}"],
    ['주문 수를 order_id.nunique()로 계산했는가?', 'O',
     f"nunique 사용. 단, 카테고리 order_count 합({int(llm_category['order_count'].sum())}) ≠ 전체 주문 수(184)라는 주의 없음"],
    ['최종 합계를 검증했는가?', 'X',
     f"총합 검증 코드 없음 → 직접 확인: LLM 합계 {llm_category['total_sales'].sum():,} = 원본 {base_total:,}"],
    ['실행 환경에서 바로 실행되는가?', 'X', '상대경로 data/raw/... → Notebook 위치에서 FileNotFoundError'],
], columns=['검토 항목', '판정', '근거'])
with pd.option_context('display.max_colwidth', None):
    display(review)
print('카테고리 금액 차이 합:', compare['sales_diff'].abs().sum(), '| 수량 차이 합:', compare['qty_diff'].abs().sum(),
      '| 주문 수 차이 합:', compare['count_diff'].abs().sum(), '| 카테고리 불일치:', (compare['_merge'] != 'both').sum())

,검토 항목,판정,근거
0,실제 컬럼명을 사용했는가?,O,"order_id, product_id, quantity, unit_price, order_status, category 모두 실제 컬럼"
1,필요한 테이블을 정확히 연결했는가?,O,"상태 ← orders.order_status, 카테고리 ← products.category, 금액 ← order_items. 불필요한 customers는 사용하지 않음"
2,필터 조건이 실제 데이터와 맞는가?,△,"'completed'는 실제 값과 일치. 단, order_status 실제 값(value_counts) 확인 단계가 없음"
3,분석 기간을 적용했는가?,X,order_date를 불러오지 않아 기간 필터 없음. 이번 데이터는 전부 기간 안(2025-07-09~2026-07-08)이라 결과만 우연히 같음
4,merge 관계가 올바른가?,O,"N:1 × 2회, validate+indicator 사용, left_only=0. 단, products 병합 '전' 행 수는 출력하지 않음"
5,completed 범위를 정확히 적용했는가?,O,"범위 내 status ['completed'], 행 수 474 = Notebook 474"
6,주문 수를 order_id.nunique()로 계산했는가?,O,"nunique 사용. 단, 카테고리 order_count 합(396) ≠ 전체 주문 수(184)라는 주의 없음"
7,최종 합계를 검증했는가?,X,"총합 검증 코드 없음 → 직접 확인: LLM 합계 148,990,000 = 원본 148,990,000"
8,실행 환경에서 바로 실행되는가?,X,상대경로 data/raw/... → Notebook 위치에서 FileNotFoundError

카테고리 금액 차이 합: 0 | 수량 차이 합: 0 | 주문 수 차이 합: 0 | 카테고리 불일치: 0

In [18]:
# ⑤ 검토 결과를 반영한 최종 코드 실행: 경로 수정 + order_status 실제 값 확인 + 분석 기간 필터 + 병합 assert + 총합 assert(병합 전 합계 기준)
llm_code_final = LLM_CODE.replace('pd.read_csv("data/raw/', 'pd.read_csv(DATA_DIR / "')
edits = [
    ('orders[["order_id", "order_status"]]', 'orders[["order_id", "order_date", "order_status"]]'),
    ('completed = df[df["order_status"] == "completed"]',
     'print("order_status 실제 값:", df["order_status"].value_counts().to_dict())\n'
     'df["order_date"] = pd.to_datetime(df["order_date"], format="%Y-%m-%d", errors="coerce")\n'
     'completed = df[(df["order_status"] == "completed") & (df["order_date"] >= START) & (df["order_date"] < END_EXCL)]\n'
     'pre_merge_total, pre_merge_rows = completed["line_total"].sum(), len(completed)'),
    ('df = df.drop(columns="_merge")',
     'assert len(df) == len(order_items) and (df["_merge"] == "left_only").sum() == 0, "orders 병합 이상"\n'
     'df = df.drop(columns="_merge")'),
    ('print("products 병합 후:", len(completed))',
     'assert len(completed) == pre_merge_rows and (completed["_merge"] == "left_only").sum() == 0, "products 병합 이상"\n'
     'print("products 병합 후:", len(completed))'),
]
for old, new in edits:
    assert old in llm_code_final, old
    llm_code_final = llm_code_final.replace(old, new)
llm_code_final += ('\nassert category_summary["total_sales"].sum() == pre_merge_total, "총합 불일치(products 병합 전 합계와 비교)"\n'
                   'print("총합 검증 PASS:", f\'{category_summary["total_sales"].sum():,}\')\n')
final_ns = {'DATA_DIR': DATA_DIR, 'START': ANALYSIS_START, 'END_EXCL': ANALYSIS_END_EXCL}
exec(llm_code_final, final_ns)
cols = ['total_sales', 'total_quantity', 'order_count']
diff = (category_sales.set_index('category')[cols].sort_index()
        .compare(final_ns['category_summary'].set_index('category')[cols].sort_index()))
print('수정 후 LLM 코드 vs Notebook category_sales 차이:', '없음' if diff.empty else diff)

orders 병합 전/후: 764 764
{'both': 764, 'left_only': 0, 'right_only': 0}
order_status 실제 값: {'completed': 474, 'cancelled': 162, 'refunded': 128}
products 병합 후: 474
{'both': 474, 'left_only': 0, 'right_only': 0}
  category  total_sales  total_quantity  order_count
3      스포츠     31743000             295           85
5     전자기기     26400000             259           60
2     생활용품     23915000             272           65
1       뷰티     23383000             223           65
4       식품     16573000             133           36
0       도서     16389000             149           52
6       패션     10587000             111           33
총합 검증 PASS: 148,990,000
수정 후 LLM 코드 vs Notebook category_sales 차이: 없음

- LLM Prompt 요약: completed 주문 기준 카테고리별 `total_sales`, `total_quantity`, `order_count` 계산 요청. key 고유성, N:1 merge + indicator, 행 수·미매칭 확인 포함
- 제안 코드 요약: `line_total` 생성 → key `is_unique` assert → orders 병합 → completed 필터 → products 병합 → 카테고리별 `sum`/`nunique`
- 실제 컬럼/범위와 맞지 않은 부분:
  1. 상대경로 `data/raw/...` 때문에 Notebook 작업 폴더(`ch04`)에서 `FileNotFoundError`가 납니다.
  2. **분석 기간 필터가 없습니다.** `order_date`를 불러오지도 않습니다. 이번 원본은 모두 분석 기간 안이라 결과가 같았을 뿐이고, 데이터가 추가되면 결과가 달라집니다. 내 Prompt에 기간을 넣지 않은 것이 원인입니다.
  3. 총합 검증이 없습니다.
  4. `order_status` 실제 값 확인 단계가 없습니다.
  5. 미매칭·행 수를 `print`만 하고 멈추지 않습니다.
- 테이블 연결 관계 검토: 상태(`orders`), 카테고리(`products`), 금액(`order_items`)을 각각 올바른 key로 N:1 연결했습니다. 이 질문에 불필요한 `customers`는 쓰지 않았습니다. **연결 관계는 정확합니다.**
- 수정한 내용(⑤ 셀에서 5가지 문제를 모두 반영하고 실행):
  - 1번 → 경로를 `DATA_DIR`로 변경
  - 2번 → `orders`에서 `order_date`를 함께 불러와 분석 기간(`2025-07-01 <= order_date < 2026-08-01`) 필터 추가
  - 3번 → 총합 `assert` 추가. products 병합 **전** completed 합계와 비교하므로 병합 중 행 복제도 잡아냄
  - 4번 → 필터 전 `order_status` 실제 값 출력
  - 5번 → 두 병합 모두 행 수 일치와 `left_only` 0을 `assert`로 확인해, 이상이 있으면 중단
- 대조 결과:
  - 경로만 고친 버전과 5가지를 모두 반영한 최종 버전 모두 Notebook `category_sales`와 차이 0
  - 최종 버전의 `order_status` 실제 값: completed 474 / cancelled 162 / refunded 128(주문 상세 행 기준)
  - 총합 검증 PASS(148,990,000)
- **최종 판단: 수정 후 사용**. 5가지를 반영한 최종 코드(⑤)가 모든 assert를 통과했고, Notebook 결과와 같다는 것을 실행으로 확인했습니다.

![LLM 코드 검증](images/step06_llm_validation.png)

### 나의 해석과 판단
- LLM 원문 코드는 경로만 고치면 숫자가 맞았습니다. 그래도 그대로 채택하지 않았습니다. **결과가 맞다는 근거가 LLM 코드 안에 없었기 때문**입니다. 맞다고 판단한 근거는 직접 만든 Notebook 결과와의 대조, 그리고 직접 추가해 실행한 기간 필터·총합 검증입니다.
- 6-1처럼 `products`만 붙여 "실행되게만" 고친 코드는 `orders` 연결이 없어 상태 필터를 적용할 수 없습니다. 합계가 255,610,000이 되어 completed 기준보다 106,620,000(약 72%) 많고, 순위도 바뀝니다(뷰티 2위). 오류 없이 그럴듯한 숫자가 나오므로 **실행 성공 ≠ 분석 성공**입니다.
- LLM은 Prompt에 쓰지 않은 조건(분석 기간, 총합 검증)을 스스로 넣지 않았습니다. 무엇을 계산하고 검증할지는 사람이 실제 데이터를 확인한 뒤 정해야 합니다.

## 7. Chapter 04 최종 인사이트

### 가장 의미 있다고 생각한 결과 2가지
1. **2025-07-01 ~ 2026-07-31 completed 상품 주문 금액 1위 카테고리는 스포츠(31,743,000, 21.31%)이고, 이 결론은 견고합니다.**
   - 2위 전자기기보다 20.2% 많습니다.
   - 카테고리마다 1위 상품을 하나씩 빼도, 완전한 월(2025-08 ~ 2026-06)만 써도 1위가 유지됩니다.
2. **주문 상태 필터는 1위는 바꾸지 않지만 중위권 순위와 금액 규모를 크게 바꿉니다.**
   - 상태 필터 전에는 뷰티가 2위(47,551,000)지만, 금액 기준 completed 비율이 49.2%라 completed 기준으로는 4위입니다.
   - 전체 금액은 255,610,000 → 148,990,000(약 42%↓)이 됩니다.

### 그 결과를 뒷받침하는 수치/표
- 4번 카테고리 집계표: `total_sales`, `customer_count`, `product_count`, `amount_per_product`
- 4번 견고성 표: 1위 상품 제외 순위(`rank_without_top`), 완전한 월 순위(`rank_full_months`), 상태 필터 전 순위(`rank_all_status`), `completed_ratio(%)`
- 5번 총합 검증표: 원본·카테고리·상품·월·고객 합계 모두 148,990,000(PASS). 위 해석의 숫자가 집계 오류에서 나온 것이 아님을 확인
- 3번 병합 셀과 6-1 셀: 상태 필터가 없으면 255,610,000

### 추가로 확인하고 싶은 질문
- 뷰티·패션·식품의 취소·환불 사유는 무엇인가? (사유 컬럼이 있는 데이터가 필요)
- 원가 데이터를 결합하면 카테고리별 마진 순위는 상품 주문 금액 순위와 같은가?
- 할인·쿠폰 정보를 반영한 실결제액 기준으로도 스포츠가 1위인가?

### 현재 결과의 한계
- 주문 300건(completed 184건) 규모의 샘플이라 중위권 카테고리 사이의 작은 차이(예: 생활용품과 뷰티 532,000 차이)는 우연한 변동일 수 있습니다.
- `total_sales`는 completed 주문의 quantity × unit_price 합계(상품 주문 금액)입니다. 할인·배송비·세금·환불 금액·매출 인식 시점이 반영되지 않아 회사 매출액·순매출·이익으로 해석할 수 없습니다.
- 취소·환불 원인에 대한 설명은 관찰된 패턴에 대한 가설입니다. 현재 데이터에 사유 컬럼이 없어 검증할 수 없습니다.

---
## 최종 제출 체크
- [x] 핵심 셀 Output이 남아 있습니다. (처음부터 끝까지 오류 없이 실행)
- [x] merge와 총합 검증 Evidence가 있습니다. (3·5번 셀, `images/step03_merge.png`, `images/step05_total_check.png`)
- [x] 결과 관찰과 해석이 구분되어 있습니다.
- [x] LLM 코드를 검증했습니다. (원문 실행 → 경로 수정 → Notebook과 대조 → 체크리스트·테이블 연결 검토 → 수정 반영 코드 재실행)
- [x] 개인정보/Secret이 없습니다. (`customers.csv` 미사용, API Key·Token 없음)
- [x] `chapter04/chapter04.ipynb`가 GitHub에서 정상 표시됩니다.
- [x] 최종 Notebook 파일 URL을 제출합니다.