# 4장. pandas로 데이터에 질문하기

이 노트북은 데이터를 선택·필터링·정렬하고, 안전하게 병합한 뒤 완료 주문 기준 요약표를 만드는 실습 자료입니다.

## 0. 제출 정보 (Chapter 04 제출 답안)

- 이름: 장태진
- GitHub ID: Taejin-AI
- 개인 저장소: `llm-data-analysis-study`
- 작성일: 2026.10.15 (2026.10.22 공식 Notebook 기반으로 재구성)
- 사용한 LLM: Claude (Anthropic)
- 실행 환경: Windows 11, 강사 저장소 공식 clone(`https://github.com/GilbertMoon/llm-data-analysis-course`, HEAD `6105f42`), 프로젝트 `.venv`(Python 3.13.1, pandas 3.0.5) 커널. 실제 경로는 1번 셀 Output에 있습니다.
- 최종 제출 URL:

```text
https://github.com/Taejin-AI/llm-data-analysis-study/blob/master/chapter04/chapter04.ipynb
```

> 작성 방식: 실습 가이드 STEP 1대로 공식 Notebook `notebooks/ch04_pandas_basic.ipynb`를 복사해 1~15번 셀을 순서대로 실행했습니다. 답안 양식 항목은 Markdown 셀로, 추가 확인 코드는 `[추가 검증]` 셀로 사이에 넣었습니다. 공식 셀 중 수정한 것은 두 개입니다. 1번 경로 탐색 셀과, 고객 이름(`name`)을 출력하던 5번 정렬 셀이며, 둘 다 셀 안에 `[수정]`으로 표시했습니다.

## 학습 목표

- 실제 컬럼명과 값의 종류를 확인한 뒤 필터링합니다.
- 수량과 단가로 주문 상세 금액을 계산합니다.
- `validate`와 `indicator`를 사용해 병합 결과를 검증합니다.
- 취소·환불 주문을 제외하고 완료 주문 기준 매출을 계산합니다.
- 개인정보를 최소화한 분석 결과를 저장합니다.

## 1. 프로젝트 루트와 실행 환경 확인

VS Code에서 Notebook을 실행하면 현재 작업 폴더가 프로젝트 루트 또는 `notebooks` 폴더일 수 있습니다. 아래 코드는 상위 폴더를 확인해 프로젝트 루트를 찾습니다.

In [1]:
from pathlib import Path
import subprocess
import sys

import pandas as pd


def find_project_root(start_path):
    start_path = Path(start_path).resolve()
    for candidate in [start_path, *start_path.parents]:
        # [수정] 개인 저장소(llm-data-analysis-study/chapter04)에서 실행해도 형제 폴더인 강사 저장소를 찾도록 추가
        for root in (candidate, candidate / 'llm-data-analysis-course'):
            if (root / 'requirements.txt').exists() and (root / 'scripts').exists():
                return root
    raise FileNotFoundError('프로젝트 루트 폴더를 찾을 수 없습니다.')


PROJECT_ROOT = find_project_root(Path.cwd())
DATA_DIR = PROJECT_ROOT / 'data' / 'raw'
REPORT_DIR = PROJECT_ROOT / 'reports'
REPORT_DIR.mkdir(parents=True, exist_ok=True)

print('Python 실행 파일:', sys.executable)
print('현재 작업 폴더:', Path.cwd())
print('프로젝트 루트:', PROJECT_ROOT)
print('데이터 폴더:', DATA_DIR)
print('결과 저장 폴더:', REPORT_DIR)

Python 실행 파일: D:\dev\llm-data-analysis-course\.venv\Scripts\python.exe
현재 작업 폴더: D:\dev\llm-data-analysis-study\chapter04
프로젝트 루트: D:\dev\llm-data-analysis-course
데이터 폴더: D:\dev\llm-data-analysis-course\data\raw
결과 저장 폴더: D:\dev\llm-data-analysis-course\reports

In [2]:
# [추가 검증] STEP 1 성공 기준과 분석 기간 고정
git = lambda *a: subprocess.run(['git', *a], cwd=PROJECT_ROOT, capture_output=True, text=True).stdout.strip()
print('.venv 커널 사용:', '.venv' in sys.executable, '| Python', sys.version.split()[0], '| pandas', pd.__version__)
print('강사 저장소 clone:', git('remote', 'get-url', 'origin'), '| HEAD', git('log', '-1', '--format=%h %ci'))
print('data/raw 공식 커밋 대비 변경:', git('status', '--short', '--', 'data/raw') or '없음')

ANALYSIS_START = pd.Timestamp('2025-07-01')
ANALYSIS_END = pd.Timestamp('2026-07-31')
ANALYSIS_END_EXCL = pd.Timestamp('2026-08-01')   # 마지막 날이 빠지지 않도록 '다음 날 미만'으로 비교
print('분석 기간:', ANALYSIS_START.date(), '~', ANALYSIS_END.date())

.venv 커널 사용: True | Python 3.13.1 | pandas 3.0.5

강사 저장소 clone: https://github.com/GilbertMoon/llm-data-analysis-course | HEAD 6105f42 2026-10-19 08:32:07 +0900
data/raw 공식 커밋 대비 변경: 없음
분석 기간: 2025-07-01 ~ 2026-07-31

## 2. 데이터 파일 확인과 불러오기

파일이 없다면 프로젝트 루트에서 `python scripts/generate_sample_data.py`를 먼저 실행하세요.

In [3]:
required_files = ['customers.csv', 'products.csv', 'orders.csv', 'order_items.csv']
missing_files = [name for name in required_files if not (DATA_DIR / name).exists()]

if missing_files:
    raise FileNotFoundError(
        '필요한 데이터 파일이 없습니다: ' + ', '.join(missing_files)
        + '. 프로젝트 루트에서 python scripts/generate_sample_data.py를 실행하세요.'
    )

customers = pd.read_csv(DATA_DIR / 'customers.csv')
products = pd.read_csv(DATA_DIR / 'products.csv')
orders = pd.read_csv(DATA_DIR / 'orders.csv')
order_items = pd.read_csv(DATA_DIR / 'order_items.csv')

print('데이터 불러오기 완료')

데이터 불러오기 완료

## 3. 데이터 구조와 필수 컬럼 확인

LLM이 작성한 코드가 실제 컬럼명과 일치하는지 먼저 확인합니다.

In [4]:
datasets = {
    'customers': customers,
    'products': products,
    'orders': orders,
    'order_items': order_items,
}

expected_columns = {
    'customers': ['customer_id', 'gender', 'age', 'city'],
    'products': ['product_id', 'product_name', 'category', 'price'],
    'orders': ['order_id', 'customer_id', 'order_date', 'order_status'],
    'order_items': ['order_id', 'product_id', 'quantity', 'unit_price'],
}

for name, df in datasets.items():
    missing = [col for col in expected_columns[name] if col not in df.columns]
    print(name, df.shape, df.columns.tolist())
    if missing:
        raise KeyError(f'{name}에 필요한 컬럼이 없습니다: {missing}')

customers (150, 6) ['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']
products (100, 4) ['product_id', 'product_name', 'category', 'price']
orders (300, 5) ['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']
order_items (764, 5) ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']

In [5]:
# [추가 검증] 실제 데이터 확인: 결측·중복·PK, 날짜 범위, 상태·카테고리 실제 값, 수량·단가 범위, FK
PK = {'customers': 'customer_id', 'products': 'product_id', 'orders': 'order_id', 'order_items': 'order_item_id'}
quality = pd.DataFrame([
    {'table': n, 'rows': len(df), 'missing_cells': int(df.isna().sum().sum()), 'duplicated_rows': int(df.duplicated().sum()),
     'pk': PK[n], 'pk_duplicated': int(df[PK[n]].duplicated().sum()), 'pk_null': int(df[PK[n]].isna().sum())}
    for n, df in datasets.items()
])
display(quality)

order_dt = pd.to_datetime(orders['order_date'], format='%Y-%m-%d', errors='coerce')
print('order_date 변환 실패:', int(order_dt.isna().sum()), '| 범위:', order_dt.min().date(), '~', order_dt.max().date(),
      '| 분석 기간 밖 주문:', int((~((order_dt >= ANALYSIS_START) & (order_dt < ANALYSIS_END_EXCL))).sum()))

display(orders['order_status'].value_counts(dropna=False).rename('orders').to_frame().T)
display(products['category'].value_counts(dropna=False).rename('products').to_frame().T)
display(order_items[['quantity', 'unit_price']].describe().loc[['count', 'min', '50%', 'max']].T
        .assign(le_zero=[int((order_items['quantity'] <= 0).sum()), int((order_items['unit_price'] <= 0).sum())],
                null=[int(order_items['quantity'].isna().sum()), int(order_items['unit_price'].isna().sum())]))

print('order_items.order_id   → orders.order_id       없는 값:', int((~order_items['order_id'].isin(orders['order_id'])).sum()))
print('order_items.product_id → products.product_id   없는 값:', int((~order_items['product_id'].isin(products['product_id'])).sum()))
print('orders.customer_id     → customers.customer_id 없는 값:', int((~orders['customer_id'].isin(customers['customer_id'])).sum()))
print('주문 상세가 없는 orders:', int((~orders['order_id'].isin(order_items['order_id'])).sum()))

,table,rows,missing_cells,duplicated_rows,pk,pk_duplicated,pk_null
0,customers,150,0,0,customer_id,0,0
1,products,100,0,0,product_id,0,0
2,orders,300,0,0,order_id,0,0
3,order_items,764,0,0,order_item_id,0,0

order_date 변환 실패: 0 | 범위: 2025-07-09 ~ 2026-07-08 | 분석 기간 밖 주문: 0

order_status  completed  cancelled  refunded
orders              184         64        52

category  스포츠  전자기기  생활용품  뷰티  도서  패션  식품
products   19    17    16  16  14  11   7

            count     min       50%       max  le_zero  null
quantity    764.0     1.0       3.0       5.0        0     0
unit_price  764.0  5000.0  111000.0  200000.0        0     0

order_items.order_id   → orders.order_id       없는 값: 0
order_items.product_id → products.product_id   없는 값: 0
orders.customer_id     → customers.customer_id 없는 값: 0
주문 상세가 없는 orders: 0

## 답안 1. 질문과 필요한 데이터 선택

### 내가 확인하려는 질문
> 분석 기간 2025-07-01 ~ 2026-07-31(주문일 `orders.order_date` 기준, 양 끝 포함) 동안 `completed` 주문의 상품 주문 금액(`quantity × unit_price` 합계)이 가장 큰 상품 카테고리는 무엇인가?

- 분석 기간은 달력 기준 13개월로 고정했습니다. 실제 주문일은 2025-07-09 ~ 2026-07-08이라 기간 필터로 빠지는 주문은 0건입니다(위 `[추가 검증]` 셀). 첫 달(2025-07, 9일부터)과 마지막 달(2026-07, 8일까지)은 부분 월이라 월별 비교에서 따로 표시합니다.

### 계산 기준
| 항목 | 정의 |
| --- | --- |
| 분석 기간 | 2025-07-01 ~ 2026-07-31 (주문일 기준, 양 끝 포함. 코드에서는 `2025-07-01 <= order_date < 2026-08-01`) |
| 포함할 주문 상태 | `order_status == "completed"`만. `cancelled`, `refunded` 제외 |
| 금액 계산식 | `line_total = quantity × unit_price` (주문 시점 단가 `order_items.unit_price` 사용. 상품 정가 `products.price`는 금액 계산에 쓰지 않음) |
| 금액의 이름 | 상품 주문 금액. 할인·쿠폰·배송비·세금·실제 결제액 정보가 없어 회계상 매출·순매출과 같다고 보지 않음. 공식 셀의 컬럼명 `total_sales`는 이 상품 주문 금액의 합계 |
| 최종 집계 기준 | `products.category`별 `sum(line_total)`, `sum(quantity)`, 주문 수 = `order_id.nunique()` |

### 사용한 파일/컬럼
| 필요한 정보 | 컬럼 | 출처 테이블 | 연결 방법 |
| --- | --- | --- | --- |
| 금액 계산 | `quantity`, `unit_price` | `order_items` | 기준 테이블 (1행 = 주문 상세 1건) |
| completed 필터 | `order_status` | `orders` | `order_items.order_id` → `orders.order_id` (N:1) |
| 분석 기간·월 | `order_date` | `orders` | 위와 같은 연결 |
| 고객별 집계 | `customer_id` | `orders` | 위와 같은 연결 |
| 카테고리·상품명 | `category`, `product_name` | `products` | `order_items.product_id` → `products.product_id` (N:1) |

- 핵심 질문에 필요한 데이터는 `order_items.csv`, `orders.csv`, `products.csv` 3개입니다. `order_items`만으로는 상태·기간·카테고리를 알 수 없어서 두 테이블을 반드시 연결해야 합니다.
- `customers.csv`는 핵심 질문에는 쓰지 않습니다. 고객별 집계에 필요한 `customer_id`가 이미 `orders`에 있기 때문입니다. 가이드의 필터 연습(STEP 4)과 고객 도시 연결(STEP 10)에서만 사용하고, 이름(`name`)은 어디에도 출력하지 않았습니다.

### 결과 관찰
- 4개 파일 모두 필요한 컬럼이 있습니다: customers (150, 6), products (100, 4), orders (300, 5), order_items (764, 5)
- 결측 셀 0, 전체 중복 행 0, PK 중복·결측 0입니다.
- `order_date`는 변환 실패 0건, 범위 2025-07-09 ~ 2026-07-08입니다.
- `order_status` 실제 값은 completed 184, cancelled 64, refunded 52 세 가지뿐입니다.
- `category` 실제 값은 7개입니다(상품 수: 스포츠 19, 전자기기 17, 생활용품 16, 뷰티 16, 도서 14, 패션 11, 식품 7).
- `quantity`는 1~5, `unit_price`는 5,000~200,000이고 0 이하 값과 결측은 없습니다.
- FK는 모두 연결됩니다(`order_items` → `orders`·`products`, `orders` → `customers` 없는 값 0). 주문 상세가 없는 주문도 0건입니다.

![분석 질문, 계산 기준, 실제 데이터 검증](images/step01_question.png)

### 나의 해석과 판단
- 필터 값 `"completed"`가 실제 값과 정확히 같습니다. 대소문자나 한글 표기가 섞여 있지 않아 표준화 없이 그대로 쓸 수 있다고 봤습니다.
- `quantity`, `unit_price`에 0·음수·결측이 없어서 `line_total`을 모든 행에 그대로 계산할 수 있습니다. 반품·증정품 처리 규칙도 필요 없습니다.
- PK가 고유하고 FK가 모두 연결되므로 N:1 병합에서 행이 복제되거나 빠지지 않는 구조입니다. 실제 결과는 답안 3에서 다시 확인했습니다.

### 업무·분석적 의미
- 기간·상태·금액식·집계 단위를 코드보다 먼저 정해 두면, 같은 데이터로 누가 다시 계산해도 같은 숫자가 나옵니다.
- 품질 확인 결과(결측·중복·0 이하 값 0건)를 남겨 두면, 나중에 결과가 이상할 때 원인을 데이터가 아니라 계산 과정에서 찾을 수 있습니다.

### 한계와 추가 확인 사항
- 할인·쿠폰·배송비·세금·실결제 금액 컬럼이 없어 상품 주문 금액이 실제 결제액과 얼마나 다른지는 알 수 없습니다.
- `order_status`는 최종 상태 하나뿐이라 언제 취소·환불되었는지는 알 수 없습니다.

## 4. 컬럼 선택과 행 필터링

이 저장소의 샘플 데이터는 도시명을 `서울`, `부산`처럼 한글로 생성합니다. 필터링 전에 실제 값을 확인합니다.

In [6]:
customer_basic = customers[['customer_id', 'gender', 'age', 'city']]
display(customer_basic.head())

print('도시별 고객 수')
display(customers['city'].value_counts())

customers_over_30 = customers[customers['age'] >= 30]
seoul_customers = customers[customers['city'] == '서울']
city_customers = customers[customers['city'].isin(['서울', '부산'])]

print('30세 이상 고객 수:', len(customers_over_30))
print('서울 고객 수:', len(seoul_customers))
print('서울 또는 부산 고객 수:', len(city_customers))

   customer_id gender  age city
0            1      F   19   광주
1            2      F   32   대구
2            3      F   61   성남
3            4      F   55   울산
4            5      F   19   부산

도시별 고객 수

city
성남    21
광주    17
부산    16
대구    15
서울    15
울산    14
인천    14
대전    14
수원    13
고양    11
Name: count, dtype: int64

30세 이상 고객 수: 111
서울 고객 수: 15
서울 또는 부산 고객 수: 31

In [7]:
# [추가 검증] 필터 값이 실제 값에 있는지, 경계값에 따라 결과가 어떻게 바뀌는지
print('필터 값 존재 여부:', {c: c in set(customers['city']) for c in ['서울', '부산']})
print('age >= 30:', int((customers['age'] >= 30).sum()), '| age > 30:', int((customers['age'] > 30).sum()),
      '| age == 30:', int((customers['age'] == 30).sum()))
print('city 고유값:', customers['city'].nunique(), '개, 앞뒤 공백 있는 값:',
      int((customers['city'] != customers['city'].str.strip()).sum()))

필터 값 존재 여부: {'서울': True, '부산': True}
age >= 30: 111 | age > 30: 109 | age == 30: 2
city 고유값: 10 개, 앞뒤 공백 있는 값: 0

## 5. 정렬과 주문 상태 확인

In [8]:
display(products.sort_values('price', ascending=False).head(10))
# [수정] 공식 셀은 customers 전체 컬럼(name 포함)을 출력합니다. 정렬 결과 확인에는 이름이 필요 없어 제외합니다.
display(customers.drop(columns=['name']).sort_values('age', ascending=False).head(10))

print('주문 상태별 건수')
display(orders['order_status'].value_counts())

    product_id product_name category   price
98          99    뷰티 상품 099       뷰티  200000
69          70    패션 상품 070       패션  198000
57          58    식품 상품 058       식품  197000
42          43    뷰티 상품 043       뷰티  197000
23          24   스포츠 상품 024      스포츠  196000
8            9   스포츠 상품 009      스포츠  193000
36          37    뷰티 상품 037       뷰티  193000
71          72    뷰티 상품 072       뷰티  189000
7            8   스포츠 상품 008      스포츠  189000
52          53  생활용품 상품 053     생활용품  188000

     customer_id gender  age city signup_date
14            15      M   69   서울  2026-06-04
8              9      M   69   서울  2025-10-19
54            55      M   69   광주  2023-07-31
78            79      M   69   부산  2023-07-14
136          137      M   68   울산  2024-11-28
45            46      M   67   대전  2026-05-13
132          133      M   67   성남  2026-05-29
123          124      M   67   대구  2024-09-24
11            12      F   66   대전  2024-09-30
57            58      F   66   성남  2025-06-14

주문 상태별 건수

order_status
completed    184
cancelled     64
refunded      52
Name: count, dtype: int64

## 6. 주문 상세 금액 만들기

`line_total`은 주문 상세 1행의 금액입니다. 주문 상태를 연결하기 전 합계는 확정 매출이 아니라 전체 주문 상세 금액입니다.

In [9]:
order_items = order_items.copy()
order_items['line_total'] = order_items['quantity'] * order_items['unit_price']

all_order_amount = order_items['line_total'].sum()
print('전체 주문 상세 금액:', all_order_amount)
display(order_items[['order_id', 'product_id', 'quantity', 'unit_price', 'line_total']].head())

전체 주문 상세 금액: 255610000

   order_id  product_id  quantity  unit_price  line_total
0         1         100         3      102000      306000
1         1          87         5       25000      125000
2         1           7         3      142000      426000
3         1           9         3      193000      579000
4         2          72         4      189000      756000

In [10]:
# [추가 검증] line_total 점검, 필터 단계별 건수, 금액 기준 정렬
print('line_total 결측:', int(order_items['line_total'].isna().sum()), '| 0 이하:', int((order_items['line_total'] <= 0).sum()),
      '| 범위:', f"{order_items['line_total'].min():,} ~ {order_items['line_total'].max():,}")
in_period = (order_dt >= ANALYSIS_START) & (order_dt < ANALYSIS_END_EXCL)
is_completed = orders['order_status'] == 'completed'
display(pd.DataFrame([
    ['전체 주문', len(orders)],
    ['① 분석 기간 내', int(in_period.sum())],
    ['② ① + order_status == completed', int((in_period & is_completed).sum())],
], columns=['조건', '주문 수']))
display(order_items.sort_values(['line_total', 'order_item_id'], ascending=[False, True]).head(5)
        [['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'line_total']])

line_total 결측: 0 | 0 이하: 0 | 범위: 5,000 ~ 1,000,000

                                조건  주문 수
0                            전체 주문   300
1                        ① 분석 기간 내   300
2  ② ① + order_status == completed   184

     order_item_id  order_id  product_id  quantity  unit_price  line_total
22              23        10          99         5      200000     1000000
85              86        39          99         5      200000     1000000
183            184        76          99         5      200000     1000000
78              79        35          70         5      198000      990000
493            494       190          70         5      198000      990000

## 답안 2. 필터링·정렬·파생 컬럼

- 적용한 필터 조건:
  - 가이드 STEP 4 연습: `age >= 30` → 111명, `city == "서울"` → 15명, `city.isin(["서울", "부산"])` → 31명. 필터 전에 `value_counts()`로 `서울`, `부산` 표기가 실제 값에 있는지 확인했습니다.
  - 핵심 질문: ① 주문일 2025-07-01 ~ 2026-07-31 → 300건 중 300건, ② `order_status == "completed"` → 184건
- 정렬 기준: 상품 `price` 내림차순(공식 셀), 주문 상세 `line_total` 내림차순(같은 값이면 `order_item_id` 오름차순으로 순서 고정)
- 만든 파생 컬럼: `line_total`
- `line_total` 계산식: `quantity × unit_price` (예: order_id 1 첫 행 3 × 102,000 = 306,000)

![필터와 파생 컬럼](images/step02_transform.png)

### 결과 관찰
- `line_total`은 764행 모두 계산됐습니다. 결측 0, 0 이하 0, 범위 5,000 ~ 1,000,000입니다.
- 기간 필터로는 한 건도 빠지지 않았고, 상태 필터로 116건(cancelled 64 + refunded 52)이 빠졌습니다.
- 금액 상위 5개 주문 상세는 모두 수량 5 × 단가 198,000 ~ 200,000입니다.
- 나이 필터는 경계값에 따라 달라집니다. `age >= 30`은 111명, `age > 30`은 109명입니다(30세 2명).

### 나의 해석과 판단
필터 기준이 바뀌면 결과가 바로 바뀝니다.
- 상태 필터를 빼면 주문 상세 764행 전체(255,610,000)가 집계되어 completed 기준보다 106,620,000 커집니다. 카테고리 순위도 바뀌어 뷰티가 4위에서 2위가 됩니다(답안 4 견고성 표).
- 기간을 완전한 월(2025-08-01 ~ 2026-06-30)로 줄이면 부분 월의 completed 주문(2025-07 8건, 2026-07 2건)이 빠지지만, 카테고리 순위 1~7위는 그대로였습니다.
- "30세 이상"처럼 경계가 있는 조건은 `>=`와 `>` 중 업무 정의에 맞는 쪽을 먼저 정해야 합니다. 이번에는 2명 차이였지만 데이터가 커지면 차이도 커집니다.
- 지금은 기간 필터가 0건을 제외하지만, 데이터가 추가되어도 결과가 바뀌지 않도록 코드에 남겼습니다.

### 업무·분석적 의미
- 같은 이름의 합계라도 어떤 필터를 거쳤는지에 따라 의미가 다릅니다. 숫자를 보고할 때는 기간·상태 조건을 함께 적어야 합니다.

### 한계와 추가 확인 사항
- 반품을 음수 수량으로 기록하는 시스템이라면 `line_total`의 의미가 달라집니다. 이번 데이터에는 음수 수량이 없습니다.

## 7. 주문 데이터 병합과 검증

`validate='many_to_one'`은 주문 상세의 동일 주문 ID는 여러 번 나올 수 있지만 주문 테이블의 주문 ID는 한 번만 나와야 한다는 뜻입니다.

In [11]:
print('orders.order_id 중복 수:', orders['order_id'].duplicated().sum())

order_sales = order_items.merge(
    orders[['order_id', 'customer_id', 'order_date', 'order_status']],
    on='order_id',
    how='left',
    validate='many_to_one',
    indicator=True,
)

print('병합 전 행 수:', len(order_items))
print('병합 후 행 수:', len(order_sales))
display(order_sales['_merge'].value_counts())

order_sales = order_sales.drop(columns='_merge')

orders.order_id 중복 수: 0

병합 전 행 수: 764
병합 후 행 수: 764

_merge
both          764
left_only       0
right_only      0
Name: count, dtype: int64

In [12]:
# [추가 검증] 병합 1 결과를 숫자로 확인
print('병합 후 order_status 결측:', int(order_sales['order_status'].isna().sum()),
      f"| line_total 합계 병합 전 {order_items['line_total'].sum():,} → 병합 후 {order_sales['line_total'].sum():,}")
assert len(order_items) == len(order_sales) and order_sales['order_status'].notna().all()

병합 후 order_status 결측:

 0 | line_total 합계 병합 전 255,610,000 → 병합 후 255,610,000

## 8. 완료 주문만 선택하기

이후의 매출 요약은 `order_status == 'completed'`인 주문만 사용합니다.

In [13]:
order_sales['order_date'] = pd.to_datetime(order_sales['order_date'], errors='coerce')
print('날짜 변환 실패:', order_sales['order_date'].isna().sum())

completed_order_sales = order_sales[
    order_sales['order_status'] == 'completed'
].copy()

completed_order_sales['order_month'] = (
    completed_order_sales['order_date'].dt.to_period('M').astype(str)
)

print('전체 주문 상세 행 수:', len(order_sales))
print('완료 주문 상세 행 수:', len(completed_order_sales))
print('완료 주문 매출:', completed_order_sales['line_total'].sum())

날짜 변환 실패: 0
전체 주문 상세 행 수: 764
완료 주문 상세 행 수: 474
완료 주문 매출: 148990000

In [14]:
# [추가 검증] 공식 셀의 completed 범위가 분석 기간(2025-07-01 ~ 2026-07-31) 안에 모두 있는지 확인
in_scope_period = (order_sales['order_date'] >= ANALYSIS_START) & (order_sales['order_date'] < ANALYSIS_END_EXCL)
print('completed 행 중 분석 기간 밖:', int((~in_scope_period[completed_order_sales.index]).sum()),
      '→ 공식 셀의 completed_order_sales = 기간 + completed 범위')
print('범위 내 order_status 값:', completed_order_sales['order_status'].unique().tolist(),
      '| 주문 수(order_id.nunique):', completed_order_sales['order_id'].nunique(),
      '| 주문일 범위:', completed_order_sales['order_date'].min().date(), '~', completed_order_sales['order_date'].max().date(),
      '| order_month 결측:', int(completed_order_sales['order_month'].isna().sum()))
print(f"범위 밖(cancelled·refunded) 금액: {order_sales['line_total'].sum() - completed_order_sales['line_total'].sum():,}")

completed 행 중 분석 기간 밖: 0 → 공식 셀의 completed_order_sales = 기간 + completed 범위
범위 내 order_status 값: ['completed'] | 주문 수(order_id.nunique): 184 | 주문일 범위: 2025-07-09 ~ 2026-07-05 | order_month 결측: 0
범위 밖(cancelled·refunded) 금액: 106,620,000

## 9. 상품 데이터 병합과 검증

In [15]:
print('products.product_id 중복 수:', products['product_id'].duplicated().sum())

completed_sales_items = completed_order_sales.merge(
    products,
    on='product_id',
    how='left',
    validate='many_to_one',
    indicator=True,
)

print('병합 전 행 수:', len(completed_order_sales))
print('병합 후 행 수:', len(completed_sales_items))
display(completed_sales_items['_merge'].value_counts())

completed_sales_items = completed_sales_items.drop(columns='_merge')

products.product_id 중복 수: 0
병합 전 행 수: 474
병합 후 행 수: 474

_merge
both          474
left_only       0
right_only      0
Name: count, dtype: int64

In [16]:
# [추가 검증] 병합 2 결과를 숫자로 확인
print('병합 후 category 결측:', int(completed_sales_items['category'].isna().sum()),
      f"| line_total 합계 병합 전 {completed_order_sales['line_total'].sum():,} → 병합 후 {completed_sales_items['line_total'].sum():,}")
print('unit_price ≠ products.price 행 수:', int((completed_sales_items['unit_price'] != completed_sales_items['price']).sum()))
assert len(completed_order_sales) == len(completed_sales_items) and completed_sales_items['category'].notna().all()

병합 후 category 결측: 0 | line_total 합계 병합 전 148,990,000 → 병합 후 148,990,000
unit_price ≠ products.price 행 수: 0

## 답안 3. merge 검증

| 병합 | key | `validate` 결과 | 병합 전 → 후 행 수 | `indicator` 결과 | key 중복 | 판정 |
| --- | --- | --- | --- | --- | --- | --- |
| `order_items` ← `orders` | `order_id` | `many_to_one` 통과 | 764 → 764 | both 764 / left_only 0 | `orders.order_id` 0 | PASS |
| completed 주문 상세 ← `products` | `product_id` | `many_to_one` 통과 | 474 → 474 | both 474 / left_only 0 | `products.product_id` 0 | PASS |
| 고객별 집계 ← `customers[['customer_id', 'city']]` | `customer_id` | `one_to_one` 통과 | 100 → 100 | `city` 결측 0 | — | PASS |

- 병합한 데이터: `order_items` + `orders`(상태·주문일·고객), completed 주문 상세 + `products`(상품명·카테고리), 고객별 집계 + `customers`(도시)
- 사용한 key: `order_id`, `product_id`, `customer_id`
- `validate` 결과: 세 병합 모두 `MergeError` 없이 통과
- `indicator` 결과: `left_only` 0, `right_only` 0 (`how='left'`라 `right_only`는 생기지 않음)
- 병합 전/후 행 수: 764 → 764, 474 → 474, 100 → 100

![merge 검증](images/step03_merge.png)

### 결과 관찰
- 모든 병합에서 행 수가 그대로이고, 미매칭과 key 중복은 0건입니다. 병합 후 `order_status`, `category`, `city` 결측도 0입니다.
- 병합 전후 `line_total` 합계가 같습니다. orders 병합 255,610,000 → 255,610,000, products 병합 148,990,000 → 148,990,000입니다.
- completed 범위는 주문 상세 474행, 주문 184건이고, 모두 분석 기간 안입니다(기간 밖 0행).
- 주문 단가 `unit_price`와 상품 정가 `price`가 다른 행은 0건입니다.

### 나의 해석과 판단
이번 병합이 안전하다고 본 근거는 네 가지입니다.
1. 오른쪽 key가 고유합니다. `validate='many_to_one'`이 이를 강제로 확인하므로 왼쪽 행이 복제될 수 없습니다.
2. 병합 전후 행 수가 같아 복제도 손실도 없습니다.
3. `left_only`가 0건이라 모든 주문 상세가 상태·기간·카테고리 정보를 받았습니다.
4. 병합 전후 금액 합계가 같습니다.

행 수 증감이 없어 따로 설명할 것은 없습니다. 행이 늘었다면 오른쪽 key 중복을, 줄었다면 `inner` 병합이나 필터 순서를 먼저 확인했을 것입니다.

### 업무·분석적 의미
잘못된 merge는 오류 없이 금액을 바꿉니다.
- 복제(과대): 상품 마스터에 같은 `product_id`가 두 번 있으면 그 상품의 주문 금액이 두 배로 잡힙니다.
- 누락(과소): `how='left'`인데 미매칭이 있으면 `order_status`가 NaN이 되어 completed 필터에서 조용히 빠집니다.

그래서 merge는 "실행 성공"이 아니라 행 수, validate, indicator, 합계로 확인해야 합니다.

### 한계와 추가 확인 사항
- `validate`는 key의 개수 관계만 확인합니다. key 값은 맞지만 다른 상품으로 잘못 매핑된 경우는 잡지 못합니다.
- 상품 마스터가 주문 시점이 아니라 현재 기준이라면, 그 사이 카테고리가 바뀐 상품이 있어도 이 데이터로는 알 수 없습니다.

## 10. 카테고리별·상품별 매출

In [17]:
category_sales = (
    completed_sales_items
    .groupby('category', as_index=False)
    .agg(
        total_quantity=('quantity', 'sum'),
        total_sales=('line_total', 'sum'),
    )
    .sort_values('total_sales', ascending=False)
)

category_sales['sales_ratio'] = (
    category_sales['total_sales'] / category_sales['total_sales'].sum() * 100
).round(2)

display(category_sales)

product_sales = (
    completed_sales_items
    .groupby(['product_id', 'product_name', 'category'], as_index=False)
    .agg(
        total_quantity=('quantity', 'sum'),
        total_sales=('line_total', 'sum'),
    )
    .sort_values('total_sales', ascending=False)
)

display(product_sales.head(10))

  category  total_quantity  total_sales  sales_ratio
3      스포츠             295     31743000        21.31
5     전자기기             259     26400000        17.72
2     생활용품             272     23915000        16.05
1       뷰티             223     23383000        15.69
4       식품             133     16573000        11.12
0       도서             149     16389000        11.00
6       패션             111     10587000         7.11

    product_id product_name category  total_quantity  total_sales
39          41   스포츠 상품 041      스포츠              35      5705000
11          12    식품 상품 012       식품              25      4375000
8            9   스포츠 상품 009      스포츠              20      3860000
70          72    뷰티 상품 072       뷰티              20      3780000
69          71  전자기기 상품 071     전자기기              23      3703000
66          68   스포츠 상품 068      스포츠              26      3640000
78          81  전자기기 상품 081     전자기기              22      3630000
10          11    패션 상품 011       패션              31      3565000
20          22  생활용품 상품 022     생활용품              29      3248000
86          89  생활용품 상품 089     생활용품              30      3090000

In [18]:
# [추가 검증] 핵심 질문: 카테고리별 completed 상품 주문 금액 + 수량·주문·고객·상품 수
category_detail = (
    completed_sales_items
    .groupby('category', as_index=False)
    .agg(total_sales=('line_total', 'sum'), total_quantity=('quantity', 'sum'), order_count=('order_id', 'nunique'),
         customer_count=('customer_id', 'nunique'), product_count=('product_id', 'nunique'))
    .sort_values('total_sales', ascending=False)
    .reset_index(drop=True)
)
category_detail['amount_ratio(%)'] = (category_detail['total_sales'] / category_detail['total_sales'].sum() * 100).round(2)
category_detail['amount_per_product'] = (category_detail['total_sales'] / category_detail['product_count']).round(0)
display(category_detail)
top = category_detail.loc[0]
print(f"답: completed 상품 주문 금액 1위 카테고리 = {top['category']} ({top['total_sales']:,}, {top['amount_ratio(%)']}%)",
      f"| 2위와 차이 {top['total_sales'] - category_detail.loc[1, 'total_sales']:,}")
print('카테고리별 order_count 합계:', category_detail['order_count'].sum(), '/ 실제 completed 주문 수:', completed_sales_items['order_id'].nunique())
print('completed 주문이 있는 상품 수:', len(product_sales), '/ 전체 상품 수:', len(products))

,category,total_sales,total_quantity,order_count,customer_count,product_count,amount_ratio(%),amount_per_product
0,스포츠,31743000,295,85,67,18,21.31,1763500.0
1,전자기기,26400000,259,60,44,17,17.72,1552941.0
2,생활용품,23915000,272,65,50,16,16.05,1494688.0
3,뷰티,23383000,223,65,53,16,15.69,1461438.0
4,식품,16573000,133,36,31,7,11.12,2367571.0
5,도서,16389000,149,52,46,13,11.00,1260692.0
6,패션,10587000,111,33,27,11,7.11,962455.0

답: completed 상품 주문 금액 1위 카테고리 = 스포츠 (31,743,000, 21.31%) | 2위와 차이 5,343,000
카테고리별 order_count 합계: 396 / 실제 completed 주문 수: 184
completed 주문이 있는 상품 수: 98 / 전체 상품 수: 100

In [19]:
# [추가 검증] 결과 견고성: ① 카테고리별 1위 상품 제외 ② 완전한 월만 ③ 상태 필터 전
prod_by_cat = (completed_sales_items.groupby(['category', 'product_id'])['line_total'].sum()
               .reset_index().sort_values(['category', 'line_total'], ascending=[True, False]))
top_prod = prod_by_cat.groupby('category').head(1).set_index('category')
robust = category_detail.set_index('category')[['total_sales']].copy()
robust['top_product_id'] = top_prod['product_id']
robust['top_product_share(%)'] = (top_prod['line_total'] / robust['total_sales'] * 100).round(1)
robust['without_top_product'] = robust['total_sales'] - top_prod['line_total']
robust['rank_all'] = robust['total_sales'].rank(ascending=False).astype(int)
robust['rank_without_top'] = robust['without_top_product'].rank(ascending=False).astype(int)

full_months = completed_sales_items[(completed_sales_items['order_date'] >= '2025-08-01') & (completed_sales_items['order_date'] < '2026-07-01')]
robust['full_months_amount'] = full_months.groupby('category')['line_total'].sum()
robust['rank_full_months'] = robust['full_months_amount'].rank(ascending=False).astype(int)

all_status = (order_sales[in_scope_period]
              .merge(products[['product_id', 'category']], on='product_id', how='left', validate='many_to_one')
              .groupby('category')['line_total'].sum())
robust['all_status_amount'] = all_status
robust['rank_all_status'] = robust['all_status_amount'].rank(ascending=False).astype(int)
robust['completed_ratio(%)'] = (robust['total_sales'] / robust['all_status_amount'] * 100).round(1)
display(robust)

top_cat = category_detail.loc[0, 'category']
t = completed_sales_items[completed_sales_items['product_id'] == robust.loc[top_cat, 'top_product_id']]
print(f"{top_cat} 1위 상품 {robust.loc[top_cat, 'top_product_id']}: 주문 {t['order_id'].nunique()}건, 고객 {t['customer_id'].nunique()}명, "
      f"행당 최대 수량 {t['quantity'].max()}, 고객 1명 최대 비중 {t.groupby('customer_id')['line_total'].sum().max() / t['line_total'].sum():.1%}, "
      f"월 최대 {t['order_month'].value_counts().max()}건({t['order_month'].value_counts().idxmax()})")

,total_sales,top_product_id,top_product_share(%),without_top_product,rank_all,rank_without_top,full_months_amount,rank_full_months,all_status_amount,rank_all_status,completed_ratio(%)
category,,,,,,,,,,,
스포츠,31743000,41,18.0,26038000,1,1,31093000,1,50174000,1,63.3
전자기기,26400000,71,14.0,22697000,2,2,23927000,2,41003000,3,64.4
생활용품,23915000,22,13.6,20667000,3,3,22238000,3,34839000,4,68.6
뷰티,23383000,72,16.2,19603000,4,4,22047000,4,47551000,2,49.2
식품,16573000,12,26.4,12198000,5,6,15650000,5,33597000,5,49.3
도서,16389000,73,18.1,13425000,6,5,15391000,6,24645000,6,66.5
패션,10587000,11,33.7,7022000,7,7,10587000,7,23801000,7,44.5

스포츠 1위 상품 41: 주문 12건, 고객 11명, 행당 최대 수량 5, 고객 1명 최대 비중 14.3%, 월 최대 4건(2026-01)

## 11. 월별 매출

In [20]:
monthly_summary = (
    completed_order_sales
    .groupby('order_month', as_index=False)
    .agg(
        total_sales=('line_total', 'sum'),
        order_count=('order_id', 'nunique'),
    )
    .sort_values('order_month')
)

monthly_summary['average_order_value'] = (
    monthly_summary['total_sales'] / monthly_summary['order_count']
).round(0)

display(monthly_summary)

   order_month  total_sales  order_count  average_order_value
0      2025-07      5869000            8             733625.0
1      2025-08     15621000           18             867833.0
2      2025-09     10190000           13             783846.0
3      2025-10     25766000           26             991000.0
4      2025-11      8812000           12             734333.0
5      2025-12     11501000           14             821500.0
6      2026-01     17423000           22             791955.0
7      2026-02      9749000           17             573471.0
8      2026-03     13429000           14             959214.0
9      2026-04     17553000           23             763174.0
10     2026-05      8063000           11             733000.0
11     2026-06      2826000            4             706500.0
12     2026-07      2188000            2            1094000.0

In [21]:
# [추가 검증] 부분 월 표시, 월별 금액이 주문 수 때문인지 완료율 때문인지
first_month, last_month = order_dt.min().strftime('%Y-%m'), order_dt.max().strftime('%Y-%m')
monthly_check = monthly_summary.assign(partial_month=monthly_summary['order_month'].isin([first_month, last_month]))
full = monthly_check[~monthly_check['partial_month']]
print(f'부분 월: {first_month}({order_dt.min().date()}부터), {last_month}({order_dt.max().date()}까지)')
print(f"완전한 월 {len(full)}개: total_sales와 order_count 상관계수 r = {full['total_sales'].corr(full['order_count']):.2f}",
      f"| 평균 주문 금액 범위 {full['average_order_value'].min():,.0f} ~ {full['average_order_value'].max():,.0f}")
period_orders = orders[in_period].assign(order_month=order_dt[in_period].dt.strftime('%Y-%m'))
monthly_status = pd.crosstab(period_orders['order_month'], period_orders['order_status'])
monthly_status['all_orders'] = monthly_status.sum(axis=1)
monthly_status['completion_rate(%)'] = (monthly_status['completed'] / monthly_status['all_orders'] * 100).round(1)
display(monthly_status)
print('전체 완료율(%):', round(is_completed.mean() * 100, 1))

부분 월: 2025-07(2025-07-09부터), 2026-07(2026-07-08까지)
완전한 월 11개: total_sales와 order_count 상관계수 r = 0.94 | 평균 주문 금액 범위 573,471 ~ 991,000

order_status  cancelled  completed  refunded  all_orders  completion_rate(%)
order_month
2025-07               3          8         4          15                53.3
2025-08               5         18         1          24                75.0
2025-09               6         13         4          23                56.5
2025-10              10         26         3          39                66.7
2025-11               4         12         7          23                52.2
2025-12               9         14         3          26                53.8
2026-01               3         22         4          29                75.9
2026-02               5         17         7          29                58.6
2026-03               6         14         1          21                66.7
2026-04               5         23         3          31                74.2
2026-05               1         11         8          20                55.0
2026-06               6          4         6          16                25.0
2026-07               1          2         1           4                50.0

전체 완료율(%): 61.3

## 12. 고객별 구매 금액

고객 ID로 먼저 집계한 뒤 고객 속성을 붙입니다. 출력에는 실제 이름 대신 익명화된 고객 라벨을 사용합니다.

In [22]:
customer_sales = (
    completed_order_sales
    .groupby('customer_id', as_index=False)
    .agg(
        order_count=('order_id', 'nunique'),
        total_sales=('line_total', 'sum'),
    )
    .sort_values('total_sales', ascending=False)
)

customer_sales = customer_sales.merge(
    customers[['customer_id', 'city']],
    on='customer_id',
    how='left',
    validate='one_to_one',
)

customer_sales['customer_label'] = 'Customer ' + customer_sales['customer_id'].astype(str)
display(customer_sales[['customer_label', 'city', 'order_count', 'total_sales']].head(10))

  customer_label city  order_count  total_sales
0   Customer 117   성남            5      4100000
1   Customer 102   고양            4      3996000
2    Customer 83   수원            4      3880000
3    Customer 30   서울            5      3590000
4    Customer 40   서울            4      3523000
5    Customer 20   인천            2      3191000
6     Customer 3   성남            2      3178000
7   Customer 111   광주            3      3153000
8    Customer 66   서울            4      3093000
9   Customer 147   부산            2      2990000

In [23]:
# [추가 검증] 고객 속성 병합(one_to_one) 결과와 고객 집중도
print('city 결측:', int(customer_sales['city'].isna().sum()), '| 행 수:', len(customer_sales), '| 저장 컬럼:', customer_sales.columns.tolist())
top10_share = customer_sales['total_sales'].head(10).sum() / customer_sales['total_sales'].sum() * 100
print('completed 주문이 있는 고객 수:', len(customer_sales), '| 주문 이력이 있는 전체 고객 수:', orders['customer_id'].nunique(),
      f'| 상위 10명 금액 비중: {top10_share:.1f}% (균등 분포라면 {10 / len(customer_sales) * 100:.0f}%)',
      f"| 1위 고객 비중: {customer_sales['total_sales'].iloc[0] / customer_sales['total_sales'].sum():.1%}")

city 결측: 0 | 행 수: 100 | 저장 컬럼: ['customer_id', 'order_count', 'total_sales', 'city', 'customer_label']
completed 주문이 있는 고객 수: 100 | 주문 이력이 있는 전체 고객 수: 126 | 상위 10명 금액 비중: 23.3% (균등 분포라면 10%) | 1위 고객 비중: 2.8%

## 답안 4. completed 주문 범위와 집계

- 분석 범위 정의: 2025-07-01 ~ 2026-07-31 주문 중 `order_status == "completed"` 184건(주문 상세 474행). `total_sales` = 이 범위의 상품 주문 금액 합계 = 148,990,000
- 카테고리별 결과: 1위 스포츠 31,743,000 (21.31%) → 전자기기 26,400,000 (17.72%) → 생활용품 23,915,000 → 뷰티 23,383,000 → 식품 16,573,000 → 도서 16,389,000 → 패션 10,587,000 (7.11%)
- 상품별 결과: 1위 스포츠 상품 041 5,705,000 (수량 35, 주문 12건). completed 주문이 있는 상품은 98개(100개 중 2개는 없음)
- 월별 결과: 최고 2025-10 25,766,000(26건), 완전한 월 중 최저 2026-06 2,826,000(4건). 부분 월은 2025-07 5,869,000(8건), 2026-07 2,188,000(2건)
- 고객별 결과: completed 주문이 있는 고객 100명(주문 이력 고객 126명 중). 1위 Customer 117(성남) 4,100,000(5건). 상위 10명 비중 23.3%

![핵심 집계 결과](images/step04_groupby.png)

### 결과 관찰
카테고리
- 질문에 대한 답: 분석 기간 completed 상품 주문 금액이 가장 큰 카테고리는 스포츠(31,743,000)입니다. 2위 전자기기보다 5,343,000(20.2%) 많습니다.
- 스포츠는 수량(295), 주문 수(85), 구매 고객 수(67), 판매 상품 수(18)도 모두 1위입니다.
- 견고성 확인(같은 기준을 모든 카테고리에 적용):
  - 카테고리마다 1위 상품을 하나씩 빼도 스포츠가 1위입니다(26,038,000 vs 전자기기 22,697,000).
  - 1위 상품 비중은 스포츠 18.0%로 7개 중 4번째입니다(패션 33.7%, 식품 26.4%, 도서 18.1%가 더 높음).
  - 1위 상품을 빼면 중위권에서 식품(5→6위)과 도서(6→5위)가 바뀝니다.
  - 완전한 월(2025-08 ~ 2026-06)만 써도 1~7위가 그대로입니다.
- 상태 필터 전 금액으로 보면 1위는 스포츠로 같지만 뷰티가 2위(47,551,000), 전자기기가 3위가 됩니다.
- completed 비율(금액 기준)은 패션 44.5% ~ 생활용품 68.6%입니다. 패션 44.5%, 뷰티 49.2%, 식품 49.3%가 50% 아래입니다.
- 카테고리별 `order_count` 합계는 396으로 실제 completed 주문 수 184보다 큽니다.

상품
- 상품 041은 주문 12건, 고객 11명에게 나뉘어 팔렸습니다. 행당 최대 수량은 5, 고객 1명의 최대 비중은 14.3%이고, 2026-01에 4건(12건 중 33%)이 몰려 있습니다.
- 상위 10개 상품 중 스포츠가 3개(041, 009, 068)입니다.

월별
- 완전한 월 11개에서 `total_sales`와 `order_count`의 상관계수는 r = 0.94입니다.
- 완전한 월의 평균 주문 금액은 573,471(2026-02) ~ 991,000(2025-10)입니다.
- 2026-06은 전체 주문 16건, 완료율 25.0%로 전체 평균(61.3%)보다 크게 낮습니다.

고객
- 상위 10명 비중 23.3%는 균등 분포(10%)의 약 2.3배입니다. 1위 고객 비중은 2.8%입니다.

### 나의 해석과 판단
- "스포츠가 1위"라는 답은 견고하다고 봤습니다. 1위 상품 제외, 완전한 월만 사용 두 조건에서 모두 1위가 유지되고 2위와 차이도 20%입니다. 상품 041도 특정 고객 쏠림은 없었습니다(최대 14.3%). 다만 2026-01에 주문의 1/3이 몰려 있어 그 달의 판촉 여부는 확인해 보고 싶습니다.
- 반면 중위권 순위는 상태 필터와 상품 제거에 민감합니다. 뷰티는 주문은 많았지만 금액의 50.8%가 취소·환불되어 2위에서 4위로 내려갑니다. 카테고리 순위는 수요와 완료율이 합쳐진 결과로 봐야 합니다.
- 카테고리 `order_count` 합계(396)가 184보다 큰 것은 오류가 아니라, 한 주문에 여러 카테고리 상품이 들어 있기 때문입니다. 카테고리별 주문 수를 더해 전체 주문 수로 쓰면 안 됩니다.
- 월별 변동은 주로 주문 수에서 나옵니다(r = 0.94). 2026-06 급감은 주문 수 감소(16건)와 완료율 하락(25%)이 겹친 결과입니다. 부분 월(2025-07, 2026-07)은 다른 달과 같은 기준으로 비교하지 않았습니다.
- 상위 10명 비중은 균등 분포보다 높지만 1명 비중은 최대 2.8%라, 고객 한 명이 빠져도 전체 금액이 크게 흔들리는 구조는 아닙니다.

### 업무·분석적 의미
- 카테고리 금액 순위는 기획전·재고 배분 우선순위의 출발점이 됩니다. 스포츠 1위는 조건을 바꿔도 유지되므로 근거로 쓸 수 있습니다.
- 뷰티·패션·식품처럼 completed 비율이 50% 아래인 카테고리는, 주문을 늘리는 것보다 취소·환불을 줄이는 쪽이 금액에 더 효과적일 수 있습니다. 원인은 데이터에 없어 확인이 필요합니다.
- 패션은 1위 상품 비중이 33.7%라 그 상품의 재고나 판매 중단 여부가 카테고리 금액에 크게 영향을 줍니다.

### 한계와 추가 확인 사항
```text
total_sales가 가장 높다 ≠ 가장 인기 있는 카테고리 ≠ 가장 수익성이 높은 카테고리
```
- 인기: 금액은 단가의 영향을 받습니다. 구매 고객 수도 스포츠가 1위(67명)였지만 재구매·만족도 데이터는 없습니다.
- 수익성: 원가·마진 데이터가 없어 이익을 계산할 수 없습니다.
- `total_sales`를 회계상 순매출과 같다고 단정할 수 없는 이유:
  1. 할인·쿠폰·포인트 정보가 없어 `unit_price`가 최종 결제가인지 알 수 없습니다.
  2. 배송비·세금 정보가 없습니다.
  3. 환불 금액 컬럼이 없어 전액 환불인지 부분 환불인지 구분할 수 없습니다.
  4. 주문일 기준이라 회계상 매출 인식 시점(배송 완료·구매 확정일)과 다를 수 있습니다.
- completed 주문 184건 규모라 중위권(생활용품 23,915,000 vs 뷰티 23,383,000처럼 차이가 작은 구간)의 순위는 우연한 변동일 수 있습니다.

In [24]:
# [추가 검증] 총합 일치: 같은 범위(기간 + completed)라면 원본 = 카테고리 = 상품 = 월 = 고객
base_total = completed_order_sales['line_total'].sum()
checks = {
    '원본 completed line_total (orders 병합 후)': base_total,
    '원본 completed line_total (products 병합 후)': completed_sales_items['line_total'].sum(),
    '카테고리별 합계': category_sales['total_sales'].sum(),
    '상품별 합계': product_sales['total_sales'].sum(),
    '월별 합계': monthly_summary['total_sales'].sum(),
    '고객별 합계': customer_sales['total_sales'].sum(),
}
total_check = pd.DataFrame({'항목': list(checks), '합계': list(checks.values())})
total_check['기준 대비 차이'] = total_check['합계'] - base_total
total_check['결과'] = total_check['기준 대비 차이'].eq(0).map({True: 'PASS', False: 'FAIL'})
display(total_check)
print('수량  : 카테고리', category_sales['total_quantity'].sum(), '/ 상품', product_sales['total_quantity'].sum(),
      '/ 원본', completed_sales_items['quantity'].sum())
print('주문수: 월별 합', monthly_summary['order_count'].sum(), '/ 고객별 합', customer_sales['order_count'].sum(),
      '/ 원본 order_id.nunique', completed_order_sales['order_id'].nunique())
print('참고  : 카테고리별 order_count 합', category_detail['order_count'].sum(), '(한 주문이 여러 카테고리 포함 → 합산 불가)')
assert (total_check['결과'] == 'PASS').all(), '총합 불일치'
print('\n총합 검증: PASS')

                                        항목         합계  기준 대비 차이    결과
0    원본 completed line_total (orders 병합 후)  148990000         0  PASS
1  원본 completed line_total (products 병합 후)  148990000         0  PASS
2                                 카테고리별 합계  148990000         0  PASS
3                                   상품별 합계  148990000         0  PASS
4                                    월별 합계  148990000         0  PASS
5                                   고객별 합계  148990000         0  PASS

수량  : 카테고리 1442 / 상품 1442 / 원본 1442
주문수: 월별 합 184 / 고객별 합 184 / 원본 order_id.nunique 184
참고  : 카테고리별 order_count 합 396 (한 주문이 여러 카테고리 포함 → 합산 불가)

총합 검증: PASS

## 답안 5. 총합 일치 검증

- 원본 completed `line_total` 합계: 148,990,000
- 카테고리 합계: 148,990,000
- 상품별 합계: 148,990,000
- 월별 합계: 148,990,000
- 고객별 합계: 148,990,000
- 차이 여부: 모든 항목 차이 0 → PASS. 수량(1,442)과 월별·고객별 `order_count` 합계(184 = `order_id.nunique()`)도 일치합니다.

![총합 검증](images/step05_total_check.png)

### 나의 해석과 판단
- 총합 검증이 필요한 이유: groupby는 같은 범위를 나눠 다시 더하는 작업이라, 어떤 기준으로 나누든 합계가 원본과 같아야 합니다. 다르면 중간에 행이 복제됐거나(merge key 중복) 빠졌거나(범위 차이, NaN key 제외) 둘 중 하나인데, 집계표만 봐서는 드러나지 않습니다.
- 특히 `groupby`는 기본값(`dropna=True`)에서 key가 NaN인 행을 조용히 뺍니다. 오류 없이 합계만 줄어들 수 있어 숫자로 비교해야 합니다.
- 주문 수는 월별·고객별처럼 한 주문이 한 그룹에만 속하는 기준에서만 합계가 맞아야 합니다. 카테고리처럼 한 주문이 여러 그룹에 걸치면 합계가 더 큰 게 정상입니다.
- 불일치 시 확인 순서:
  1. 비교한 DataFrame들이 같은 범위(기간 + completed)인지 확인합니다.
  2. 병합 전후 행 수와 오른쪽 key 중복 수를 봅니다(복제).
  3. `_merge`의 `left_only`와 병합 후 NaN 수를 봅니다(미매칭).
  4. groupby key(`category`, `order_month`, `customer_id`)의 NaN 수를 봅니다(조용한 제외).
  5. 차이 금액과 같은 금액의 행이나 주문을 찾아 원인을 특정합니다.

## 13. 결과 저장하기

In [25]:
outputs = {
    'ch04_category_sales.csv': category_sales,
    'ch04_product_sales.csv': product_sales,
    'ch04_monthly_sales.csv': monthly_summary,
    'ch04_customer_sales.csv': customer_sales,
}

for filename, df in outputs.items():
    path = REPORT_DIR / filename
    df.to_csv(path, index=False, encoding='utf-8-sig')
    print(filename, path.exists(), path.stat().st_size)

ch04_category_sales.csv True 254
ch04_product_sales.csv True 4409
ch04_monthly_sales.csv True 442
ch04_customer_sales.csv True 3387

In [26]:
# [추가 검증] 저장한 CSV를 다시 읽어 확인
rows = []
for filename, df in outputs.items():
    check = pd.read_csv(REPORT_DIR / filename)
    rows.append({'file': filename, 'shape': check.shape, 'columns_same': check.columns.tolist() == df.columns.tolist(),
                 'total_sales_same': check['total_sales'].sum() == df['total_sales'].sum(), 'name 컬럼': 'name' in check.columns})
display(pd.DataFrame(rows))

                      file     shape  columns_same  total_sales_same  name 컬럼
0  ch04_category_sales.csv    (7, 4)          True              True    False
1   ch04_product_sales.csv   (98, 5)          True              True    False
2   ch04_monthly_sales.csv   (13, 4)          True              True    False
3  ch04_customer_sales.csv  (100, 5)          True              True    False

- 4개 CSV가 모두 저장됐고, 다시 읽었을 때 컬럼과 `total_sales` 합계가 저장 전과 같았습니다. 고객 결과에는 `customer_id`, `city`, `Customer N` 라벨만 있고 이름은 없습니다.
- 결과 CSV(`reports/ch04_*.csv`)는 강사 저장소의 실행 산출물이라 개인 저장소에는 올리지 않았습니다. 같은 데이터로 Notebook을 다시 실행하면 같은 파일이 만들어집니다.

## 14. LLM 코드 검증 연습

```text
LLM이 다음 코드를 제안했습니다.

category_sales = order_items.groupby('category')['line_total'].sum()

현재 데이터에서 이 코드가 바로 실행 가능한지 검토해 주세요.
category 컬럼의 위치, 주문 상태 필터링, merge validate와 indicator를 포함해
안전한 수정 코드와 검증 순서를 설명해 주세요.
```

### 14-1. 공식 예시 코드 점검
공식 Notebook 14번의 LLM 제안 코드 `order_items.groupby('category')['line_total'].sum()`을 실제 데이터에 실행해 봤습니다.

In [27]:
# [추가 검증] 14번 LLM 예시 코드를 그대로 실행
try:
    order_items.groupby('category')['line_total'].sum()
except KeyError as e:
    print('KeyError 발생:', e)
print("order_items에 category 컬럼:", 'category' in order_items.columns, "| products에 category 컬럼:", 'category' in products.columns)
naive = (order_items.merge(products[['product_id', 'category']], on='product_id')
         .groupby('category')['line_total'].sum())
print('상태 필터 없는 카테고리 합계:', f'{naive.sum():,}', '/ completed 기준:', f"{category_sales['total_sales'].sum():,}")
print('필터 없는 순위:', naive.sort_values(ascending=False).head(3).to_dict())

KeyError 발생: 'category'
order_items에 category 컬럼: False | products에 category 컬럼: True

상태 필터 없는 카테고리 합계: 255,610,000 / completed 기준: 148,990,000
필터 없는 순위: {'스포츠': 50174000, '뷰티': 47551000, '전자기기': 41003000}

### 14-2. 이번 과제 질문으로 LLM에 코드 요청
- 사용 LLM: Claude (Anthropic)
- Prompt:

```text
orders.csv, order_items.csv, products.csv를 사용해
completed 주문 기준 카테고리별 total_sales와 total_quantity를 계산하는 pandas 코드를 작성해 주세요.

- line_total = quantity × unit_price
- orders.order_id, products.product_id 고유성 확인
- many-to-one merge + indicator
- 병합 전후 행 수와 미매칭 확인
- completed 주문만 필터링
- 카테고리별 고유 주문 수(order_count)도 계산
- 결과를 회계상 순매출이라고 단정하지 않기
```

아래 `LLM_CODE`가 LLM 응답 코드 원문입니다. 검토 순서는 ① 원문 실행 → ② 경로만 고쳐 실행하고 Notebook 결과와 대조 → ③ 체크리스트와 테이블 연결 관계로 검토 → ④ 찾은 문제를 반영한 코드로 재실행입니다. LLM 코드는 별도 namespace에서 실행해 Notebook 변수를 덮어쓰지 않게 했습니다.

In [28]:
LLM_CODE = r"""
import pandas as pd

orders = pd.read_csv("data/raw/orders.csv")
order_items = pd.read_csv("data/raw/order_items.csv")
products = pd.read_csv("data/raw/products.csv")

# 1) 주문 상세 금액
order_items["line_total"] = order_items["quantity"] * order_items["unit_price"]

# 2) 키 고유성 확인
assert orders["order_id"].is_unique
assert products["product_id"].is_unique

# 3) 주문 상태 연결 (many-to-one)
df = order_items.merge(
    orders[["order_id", "order_status"]],
    on="order_id", how="left", validate="many_to_one", indicator=True,
)
print("orders 병합 전/후:", len(order_items), len(df))
print(df["_merge"].value_counts().to_dict())
df = df.drop(columns="_merge")

# 4) 완료 주문만
completed = df[df["order_status"] == "completed"]

# 5) 상품 카테고리 연결 (many-to-one)
completed = completed.merge(
    products[["product_id", "category"]],
    on="product_id", how="left", validate="many_to_one", indicator=True,
)
print("products 병합 후:", len(completed))
print(completed["_merge"].value_counts().to_dict())

# 6) 카테고리별 집계
category_summary = (
    completed.groupby("category", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        total_quantity=("quantity", "sum"),
        order_count=("order_id", "nunique"),
    )
    .sort_values("total_sales", ascending=False)
)
print(category_summary)
# 참고: total_sales는 completed 주문의 quantity × unit_price 합계이며 회계상 순매출이 아닙니다.
"""

# ① 원문 그대로 실행
try:
    exec(LLM_CODE, {})
except FileNotFoundError as e:
    print('① 원문 실행 결과 → FileNotFoundError:', e)
    print('   현재 작업 폴더:', Path.cwd().name, '(data/raw가 이 폴더 아래에 없음)')

① 원문 실행 결과 → FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/orders.csv'
   현재 작업 폴더: chapter04 (data/raw가 이 폴더 아래에 없음)

In [29]:
# ② 경로만 DATA_DIR로 수정해서 실행 (로직은 원문 그대로) → ③ Notebook 결과와 대조
llm_code_fixed = LLM_CODE.replace('pd.read_csv("data/raw/', 'pd.read_csv(DATA_DIR / "')
llm_ns = {'DATA_DIR': DATA_DIR}
print('② 경로 수정 후 실행 출력 ↓')
exec(llm_code_fixed, llm_ns)
llm_category = llm_ns['category_summary']
compare = category_detail[['category', 'total_sales', 'total_quantity', 'order_count']].merge(
    llm_category, on='category', how='outer', suffixes=('_notebook', '_llm'), indicator=True)
compare['sales_diff'] = compare['total_sales_llm'] - compare['total_sales_notebook']
compare['qty_diff'] = compare['total_quantity_llm'] - compare['total_quantity_notebook']
compare['count_diff'] = compare['order_count_llm'] - compare['order_count_notebook']
print('\n③ Notebook 카테고리 집계와 대조')
display(compare[['category', 'total_sales_notebook', 'total_sales_llm', 'sales_diff', 'qty_diff', 'count_diff', '_merge']])

② 경로 수정 후 실행 출력 ↓

orders 병합 전/후: 764 764
{'both': 764, 'left_only': 0, 'right_only': 0}
products 병합 후: 474
{'both': 474, 'left_only': 0, 'right_only': 0}
  category  total_sales  total_quantity  order_count
3      스포츠     31743000             295           85
5     전자기기     26400000             259           60
2     생활용품     23915000             272           65
1       뷰티     23383000             223           65
4       식품     16573000             133           36
0       도서     16389000             149           52
6       패션     10587000             111           33

③ Notebook 카테고리 집계와 대조

,category,total_sales_notebook,total_sales_llm,sales_diff,qty_diff,count_diff,_merge
0,도서,16389000,16389000,0,0,0,both
1,뷰티,23383000,23383000,0,0,0,both
2,생활용품,23915000,23915000,0,0,0,both
3,스포츠,31743000,31743000,0,0,0,both
4,식품,16573000,16573000,0,0,0,both
5,전자기기,26400000,26400000,0,0,0,both
6,패션,10587000,10587000,0,0,0,both

In [30]:
# ④ 체크리스트와 테이블 연결 관계로 LLM 코드 직접 검토
llm_completed = llm_ns['completed']
llm_dates = pd.to_datetime(llm_ns['orders']['order_date'])
review = pd.DataFrame([
    ['실제 컬럼명을 사용했는가?', 'O', 'order_id, product_id, quantity, unit_price, order_status, category 모두 실제 컬럼'],
    ['필요한 테이블을 정확히 연결했는가?', 'O', '상태 ← orders.order_status, 카테고리 ← products.category, 금액 ← order_items. customers는 사용하지 않음'],
    ['필터 값이 실제 데이터와 맞는가?', '△', "'completed'는 실제 값과 일치. 단, order_status 실제 값 확인 단계가 없음"],
    ['분석 기간을 적용했는가?', 'X', f'order_date를 불러오지 않음. 이번 데이터는 모두 기간 안({llm_dates.min().date()}~{llm_dates.max().date()})이라 결과만 같음'],
    ['merge 관계가 올바른가?', 'O', f"N:1 × 2회, validate+indicator 사용, left_only={int((llm_completed['_merge'] == 'left_only').sum())}. 단, products 병합 전 행 수는 출력하지 않음"],
    ['completed 범위를 정확히 적용했는가?', 'O', f"범위 내 status {llm_completed['order_status'].unique().tolist()}, 행 수 {len(llm_completed)} = Notebook {len(completed_sales_items)}"],
    ['주문 수를 order_id.nunique()로 계산했는가?', 'O', f"nunique 사용. 단, 카테고리 order_count 합({int(llm_category['order_count'].sum())}) ≠ 전체 주문 수(184)라는 주의 없음"],
    ['최종 합계를 검증했는가?', 'X', f"총합 검증 코드 없음 → 직접 확인: LLM 합계 {llm_category['total_sales'].sum():,} = 원본 {base_total:,}"],
    ['실행 환경에서 바로 실행되는가?', 'X', '상대경로 data/raw/... → Notebook 위치에서 FileNotFoundError'],
], columns=['검토 항목', '판정', '근거'])
with pd.option_context('display.max_colwidth', None):
    display(review)

,검토 항목,판정,근거
0,실제 컬럼명을 사용했는가?,O,"order_id, product_id, quantity, unit_price, order_status, category 모두 실제 컬럼"
1,필요한 테이블을 정확히 연결했는가?,O,"상태 ← orders.order_status, 카테고리 ← products.category, 금액 ← order_items. customers는 사용하지 않음"
2,필터 값이 실제 데이터와 맞는가?,△,"'completed'는 실제 값과 일치. 단, order_status 실제 값 확인 단계가 없음"
3,분석 기간을 적용했는가?,X,order_date를 불러오지 않음. 이번 데이터는 모두 기간 안(2025-07-09~2026-07-08)이라 결과만 같음
4,merge 관계가 올바른가?,O,"N:1 × 2회, validate+indicator 사용, left_only=0. 단, products 병합 전 행 수는 출력하지 않음"
5,completed 범위를 정확히 적용했는가?,O,"범위 내 status ['completed'], 행 수 474 = Notebook 474"
6,주문 수를 order_id.nunique()로 계산했는가?,O,"nunique 사용. 단, 카테고리 order_count 합(396) ≠ 전체 주문 수(184)라는 주의 없음"
7,최종 합계를 검증했는가?,X,"총합 검증 코드 없음 → 직접 확인: LLM 합계 148,990,000 = 원본 148,990,000"
8,실행 환경에서 바로 실행되는가?,X,상대경로 data/raw/... → Notebook 위치에서 FileNotFoundError

In [31]:
# ⑤ 검토 결과를 반영한 최종 코드: 경로 + order_status 실제 값 확인 + 분석 기간 + 병합 assert + 총합 assert
llm_code_final = LLM_CODE.replace('pd.read_csv("data/raw/', 'pd.read_csv(DATA_DIR / "')
edits = [
    ('orders[["order_id", "order_status"]]', 'orders[["order_id", "order_date", "order_status"]]'),
    ('completed = df[df["order_status"] == "completed"]',
     'print("order_status 실제 값:", df["order_status"].value_counts().to_dict())\n'
     'df["order_date"] = pd.to_datetime(df["order_date"], format="%Y-%m-%d", errors="coerce")\n'
     'completed = df[(df["order_status"] == "completed") & (df["order_date"] >= START) & (df["order_date"] < END_EXCL)]\n'
     'pre_merge_total, pre_merge_rows = completed["line_total"].sum(), len(completed)'),
    ('df = df.drop(columns="_merge")',
     'assert len(df) == len(order_items) and (df["_merge"] == "left_only").sum() == 0, "orders 병합 이상"\n'
     'df = df.drop(columns="_merge")'),
    ('print("products 병합 후:", len(completed))',
     'assert len(completed) == pre_merge_rows and (completed["_merge"] == "left_only").sum() == 0, "products 병합 이상"\n'
     'print("products 병합 후:", len(completed))'),
]
for old, new in edits:
    assert old in llm_code_final, old
    llm_code_final = llm_code_final.replace(old, new)
llm_code_final += ('\nassert category_summary["total_sales"].sum() == pre_merge_total, "총합 불일치"\n'
                   'print("총합 검증 PASS:", f\'{category_summary["total_sales"].sum():,}\')\n')
final_ns = {'DATA_DIR': DATA_DIR, 'START': ANALYSIS_START, 'END_EXCL': ANALYSIS_END_EXCL}
exec(llm_code_final, final_ns)
cols = ['total_sales', 'total_quantity', 'order_count']
diff = (category_detail.set_index('category')[cols].sort_index()
        .compare(final_ns['category_summary'].set_index('category')[cols].sort_index()))
print('수정 후 LLM 코드 vs Notebook 카테고리 집계 차이:', '없음' if diff.empty else diff)

orders 병합 전/후: 764 764
{'both': 764, 'left_only': 0, 'right_only': 0}
order_status 실제 값: {'completed': 474, 'cancelled': 162, 'refunded': 128}
products 병합 후: 474
{'both': 474, 'left_only': 0, 'right_only': 0}
  category  total_sales  total_quantity  order_count
3      스포츠     31743000             295           85
5     전자기기     26400000             259           60
2     생활용품     23915000             272           65
1       뷰티     23383000             223           65
4       식품     16573000             133           36
0       도서     16389000             149           52
6       패션     10587000             111           33
총합 검증 PASS: 148,990,000
수정 후 LLM 코드 vs Notebook 카테고리 집계 차이: 없음

## 답안 6. LLM pandas 코드 검증

- LLM Prompt 요약: completed 주문 기준 카테고리별 `total_sales`, `total_quantity`, `order_count` 계산 요청. key 고유성, N:1 merge + indicator, 행 수·미매칭 확인 포함
- 제안 코드 요약: `line_total` 생성 → key `is_unique` assert → orders 병합 → completed 필터 → products 병합 → 카테고리별 `sum`/`nunique`
- 실제 컬럼/범위와 맞지 않은 부분:
  1. 상대경로 `data/raw/...` 때문에 Notebook 작업 폴더(`chapter04`)에서 `FileNotFoundError`가 납니다.
  2. 분석 기간 필터가 없고 `order_date`를 불러오지도 않습니다. 이번 원본은 모두 기간 안이라 결과가 같았을 뿐입니다. 내 Prompt에 기간을 넣지 않은 것이 원인입니다.
  3. 총합 검증이 없습니다.
  4. `order_status` 실제 값을 확인하는 단계가 없습니다.
  5. 미매칭·행 수를 `print`만 하고 이상이 있어도 멈추지 않습니다.
- 테이블 연결 관계: 상태(`orders`), 카테고리(`products`), 금액(`order_items`)을 올바른 key로 N:1 연결했고, 이 질문에 불필요한 `customers`는 쓰지 않았습니다. 연결 관계는 정확합니다.
- 수정한 내용(⑤ 셀에서 5가지 모두 반영해 실행):
  - 1번 → 경로를 `DATA_DIR`로 변경
  - 2번 → `order_date`를 함께 불러와 분석 기간(`2025-07-01 <= order_date < 2026-08-01`) 필터 추가
  - 3번 → 총합 `assert` 추가. products 병합 전 합계와 비교해서 병합 중 복제도 잡도록 함
  - 4번 → 필터 전에 `order_status` 실제 값 출력
  - 5번 → 두 병합 모두 행 수 일치와 `left_only` 0을 `assert`로 확인
- 대조 결과: 경로만 고친 버전과 최종 버전 모두 Notebook 카테고리 집계와 차이 0. 최종 버전의 `order_status` 실제 값은 completed 474 / cancelled 162 / refunded 128(주문 상세 행 기준), 총합 검증 PASS(148,990,000)
- 최종 판단: 수정 후 사용

![LLM 코드 검증](images/step06_llm_validation.png)

### 나의 해석과 판단
- LLM 원문 코드는 경로만 고치면 숫자가 맞았지만 그대로 쓰지 않았습니다. 결과가 맞다는 근거가 LLM 코드 안에 없었기 때문입니다. 맞다고 판단한 근거는 직접 만든 Notebook 결과와의 대조, 그리고 직접 추가한 기간 필터·총합 검증입니다.
- 14-1처럼 `products`만 붙여 실행되게만 고친 코드는 `orders` 연결이 없어 상태 필터를 걸 수 없습니다. 합계가 255,610,000으로 completed 기준보다 106,620,000(약 72%) 많고 순위도 바뀝니다(뷰티 2위). 오류 없이 그럴듯한 숫자가 나오므로 실행 성공이 분석 성공은 아닙니다.
- LLM은 Prompt에 쓰지 않은 조건(분석 기간, 총합 검증)을 스스로 넣지 않았습니다. 무엇을 계산하고 검증할지는 실제 데이터를 확인한 사람이 정해야 합니다.

## 15. 실습 과제

1. 40세 이상 고객을 추출합니다.
2. 상품 가격이 낮은 순서대로 10개를 출력합니다.
3. 결제수단별 주문 수와 비율을 계산합니다.
4. 카테고리별 평균 상품 가격을 계산합니다.
5. 완료 주문과 전체 주문의 금액 차이를 계산합니다.
6. 병합 검증을 포함한 고객별 구매 금액 코드 요청 프롬프트를 작성합니다.

In [32]:
# 과제 코드를 아래에 작성하세요.

# 과제 1. 40세 이상 고객 추출 (이름 제외)
customers_over_40 = customers.loc[customers['age'] >= 40, ['customer_id', 'gender', 'age', 'city']]
print('과제 1. 40세 이상 고객 수:', len(customers_over_40), '/', len(customers))
display(customers_over_40.head())

# 과제 2. 상품 가격이 낮은 순서대로 10개
print('과제 2. 가격 하위 10개')
display(products.sort_values(['price', 'product_id']).head(10))

# 과제 3. 결제수단별 주문 수와 비율 (전체 주문 300건 기준)
task3 = orders['payment_method'].value_counts().rename('order_count').to_frame()
task3['ratio(%)'] = (task3['order_count'] / task3['order_count'].sum() * 100).round(2)
print('과제 3. 결제수단별 주문 수 합계:', int(task3['order_count'].sum()))
display(task3)

# 과제 4. 카테고리별 평균 상품 가격 (상품 마스터 price 기준)
task4 = products.groupby('category')['price'].agg(product_count='count', avg_price='mean').round(0).sort_values('avg_price', ascending=False)
print('과제 4. 카테고리별 평균 상품 가격')
display(task4)

# 과제 5. 완료 주문과 전체 주문의 금액 차이
all_amount = order_sales['line_total'].sum()
completed_amount = completed_order_sales['line_total'].sum()
by_status = order_sales.groupby('order_status')['line_total'].sum()
print(f'과제 5. 전체 {all_amount:,} - completed {completed_amount:,} = {all_amount - completed_amount:,}',
      f'(completed 비율 {completed_amount / all_amount * 100:.2f}%) | 상태별: {by_status.to_dict()}')

과제 1. 40세 이상 고객 수: 78 / 150

   customer_id gender  age city
2            3      F   61   성남
3            4      F   55   울산
6            7      F   53   인천
8            9      M   69   서울
9           10      F   62   울산

과제 2. 가격 하위 10개

    product_id product_name category  price
5            6  전자기기 상품 006     전자기기   5000
27          28    뷰티 상품 028       뷰티   5000
97          98   스포츠 상품 098      스포츠  10000
46          47  생활용품 상품 047     생활용품  11000
94          95  전자기기 상품 095     전자기기  20000
49          50    뷰티 상품 050       뷰티  23000
82          83  전자기기 상품 083     전자기기  24000
86          87    도서 상품 087       도서  25000
41          42    패션 상품 042       패션  28000
58          59    뷰티 상품 059       뷰티  32000

과제 3. 결제수단별 주문 수 합계: 300

                order_count  ratio(%)
payment_method
kakao_pay                79     26.33
naver_pay                77     25.67
bank_transfer            74     24.67
card                     70     23.33

과제 4. 카테고리별 평균 상품 가격

          product_count  avg_price
category
식품                    7   137143.0
뷰티                   16   117688.0
패션                   11   115909.0
스포츠                  19   111579.0
도서                   14   106857.0
전자기기                 17   101588.0
생활용품                 16    96438.0

과제 5. 전체 255,610,000 - completed 148,990,000 = 106,620,000 (completed 비율 58.29%) | 상태별: {'cancelled': 62181000, 'completed': 148990000, 'refunded': 44439000}

### 15번 실습 과제 답안

- 과제 1: 40세 이상 고객은 150명 중 78명입니다. 출력에서 이름은 제외했습니다.
- 과제 2: 가격이 가장 낮은 상품은 5,000원(전자기기 006, 뷰티 028)이고, 하위 10개는 5,000 ~ 32,000원입니다. 같은 가격은 `product_id` 순으로 고정했습니다.
- 과제 3: 전체 주문 300건 기준 kakao_pay 79건(26.33%), naver_pay 77건(25.67%), bank_transfer 74건(24.67%), card 70건(23.33%)으로 고르게 나뉩니다.
- 과제 4: 상품 마스터 `price` 평균은 식품 137,143이 가장 높고 생활용품 96,438이 가장 낮습니다. 식품은 상품이 7개뿐이라 평균이 몇 개 상품에 크게 좌우됩니다.
- 과제 5: 전체 주문 상세 금액 255,610,000 - completed 148,990,000 = 106,620,000입니다(completed 비율 58.29%, cancelled 62,181,000, refunded 44,439,000).
- 과제 6: 병합 검증을 포함한 고객별 구매 금액 코드 요청 Prompt

```text
orders.csv와 order_items.csv로 고객별 completed 상품 주문 금액을 계산하는 pandas 코드를 작성해 주세요.
분석 기간: order_date 2025-07-01 ~ 2026-07-31 (양 끝 포함)

- line_total = quantity × unit_price
- orders.order_id 고유성 확인 후 order_items ← orders many_to_one merge, indicator=True
- 병합 전후 행 수와 left_only 건수를 출력하고 이상이 있으면 assert로 중단
- order_status 실제 값을 먼저 출력한 뒤 completed만 필터링
- customer_id별 order_count(order_id.nunique)와 total_sales 계산
- 도시가 필요하면 customers[['customer_id', 'city']]만 one_to_one으로 연결 (이름 등 개인정보 컬럼은 불러오지 않기)
- 고객별 total_sales 합계가 completed 전체 합계와 같은지 검증
- 결과를 회계상 매출이라고 부르지 않기
```

## 정리

이번 장에서는 실제 값 확인, 컬럼 선택, 필터링, 정렬, 파생 컬럼, 병합 검증, 완료 주문 기준 집계, CSV 저장 과정을 수행했습니다. 다음 장에서는 결측치, 중복, 타입 오류, 날짜 형식, 이상값 후보를 다루는 데이터 전처리로 이어집니다.

## 답안 7. Chapter 04 최종 인사이트

### 가장 의미 있다고 생각한 결과 2가지
1. 2025-07-01 ~ 2026-07-31 completed 상품 주문 금액 1위 카테고리는 스포츠(31,743,000, 21.31%)이고, 조건을 바꿔도 유지됩니다.
   - 2위 전자기기보다 20.2% 많습니다.
   - 카테고리마다 1위 상품을 하나씩 빼도, 완전한 월(2025-08 ~ 2026-06)만 써도 1위입니다.
2. 주문 상태 필터는 1위는 바꾸지 않지만 중위권 순위와 금액 규모를 크게 바꿉니다.
   - 상태 필터 전에는 뷰티가 2위(47,551,000)지만, 금액 기준 completed 비율이 49.2%라 completed 기준으로는 4위입니다.
   - 전체 금액은 255,610,000 → 148,990,000(약 42% 감소)이 됩니다.

### 그 결과를 뒷받침하는 수치/표
- 답안 4 카테고리 집계표: 금액, 고객 수, 상품 수, 상품당 금액
- 답안 4 견고성 표: 1위 상품 제외 순위, 완전한 월 순위, 상태 필터 전 순위, completed 비율
- 답안 5 총합 검증표: 원본·카테고리·상품·월·고객 합계 모두 148,990,000(PASS). 위 숫자가 집계 오류에서 나온 것이 아님을 확인
- 14-1 셀과 과제 5: 상태 필터가 없으면 255,610,000

### 추가로 확인하고 싶은 질문
- 뷰티·패션·식품의 취소·환불 사유는 무엇인가? (사유 컬럼이 있는 데이터가 필요)
- 2026-06 완료율 25%는 특정 결제수단·카테고리에 몰려 있었나?
- 원가 데이터를 붙이면 카테고리별 마진 순위도 상품 주문 금액 순위와 같은가?

### 현재 결과의 한계
- 주문 300건(completed 184건) 규모라 중위권 카테고리 사이의 작은 차이(예: 생활용품과 뷰티 532,000 차이)는 우연한 변동일 수 있습니다.
- `total_sales`는 completed 주문의 quantity × unit_price 합계(상품 주문 금액)입니다. 할인·배송비·세금·환불 금액·매출 인식 시점이 반영되지 않아 회사 매출액이나 이익으로 해석할 수 없습니다.
- 취소·환불 원인에 대한 설명은 가설입니다. 사유 컬럼이 없어 검증할 수 없습니다.

In [33]:
# [추가 검증] Chapter 04 완료 Evidence 자동 점검
evidence = {
    'Notebook 실행 (.venv 커널, 강사 저장소 clone)': '.venv' in sys.executable and git('remote', 'get-url', 'origin').endswith('llm-data-analysis-course'),
    '필터 값이 실제 값에 존재': {'서울', '부산'} <= set(customers['city']) and 'completed' in set(orders['order_status']),
    'merge 검증 (행 수·validate·indicator)': len(order_items) == len(order_sales) and len(completed_order_sales) == len(completed_sales_items),
    'completed 범위만 사용': completed_order_sales['order_status'].eq('completed').all(),
    '총합 검증 PASS': bool((total_check['결과'] == 'PASS').all()),
    '결과 CSV 재확인': all(r['columns_same'] and r['total_sales_same'] for r in rows),
    '출력·저장 결과에 name 없음': not any(r['name 컬럼'] for r in rows),
    'LLM 코드 수정 후 Notebook과 일치': diff.empty,
}
for item, ok in evidence.items():
    print(f'{"PASS" if ok else "FAIL"}  {item}')

PASS  Notebook 실행 (.venv 커널, 강사 저장소 clone)
PASS  필터 값이 실제 값에 존재
PASS  merge 검증 (행 수·validate·indicator)
PASS  completed 범위만 사용
PASS  총합 검증 PASS
PASS  결과 CSV 재확인
PASS  출력·저장 결과에 name 없음
PASS  LLM 코드 수정 후 Notebook과 일치

## 최종 제출 체크
- [x] 핵심 셀 Output이 남아 있습니다. (공식 셀 포함 처음부터 끝까지 오류 없이 실행)
- [x] merge와 총합 검증 Evidence가 있습니다. (답안 3·5, `images/step03_merge.png`, `images/step05_total_check.png`)
- [x] 결과 관찰과 해석이 구분되어 있습니다.
- [x] LLM 코드를 검증했습니다. (원문 실행 → 경로 수정 → Notebook과 대조 → 체크리스트 검토 → 수정 코드 재실행)
- [x] 개인정보/Secret이 없습니다. (`name` 미출력·미저장, API Key·Token 없음)
- [x] `chapter04/chapter04.ipynb`가 GitHub에서 정상 표시됩니다.
- [x] 최종 Notebook 파일 URL을 제출합니다.